<head>
<!-- Start css3menu.com HEAD section -->
<link rel="stylesheet" href="http://pgoh13.com/test_menu_files/css3menu1/style.css" type="text/css" />
<!-- End css3menu.com HEAD section -->



</head>


<!-- FreeFind Begin No Index -->

<!-- Start css3menu.com BODY section id=1 -->

<nav>
<a href="http://pgoh13.com" rel="nofollow"><img alt="The World At Your Fingertips from pgoh13" title="The World At Your Fingertips from pgoh13" src="http://pgoh13.com/site_banner.gif"></a>
<br>
<ul id="css3menu1" class="topmenu">
	<li class="topfirst"><a href="http://pgoh13.com/tourist_destinations.php" rel="nofollow" style="height:18px;line-height:18px;"><span>TRAVEL</span></a>
	<ul>
		<li><a href="http://pgoh13.com/europe.php" rel="nofollow"><span>Europe</span></a>
		<ul>
<li><a href="http://pgoh13.com/bruges.html" rel="nofollow">Bruges</a></li>
                <li><a href="http://pgoh13.com/krakow.php" rel="nofollow">Krakow</a></li>
		<li><a href="http://pgoh13.com/riga.php" rel="nofollow">Riga</a></li>
		<li><a href="http://pgoh13.com/berlin.php" rel="nofollow">Berlin</a></li>
		<li><a href="http://pgoh13.com/milan.php" rel="nofollow">Milan</a></li>	
		<li><a href="http://pgoh13.com/lisbon.php" rel="nofollow">Lisbon</a></li>
			<li><a href="http://pgoh13.com/dublin.php" rel="nofollow">Dublin</a></li>
			<li><a href="http://pgoh13.com/sicily" rel="nofollow">Sicily</a></li>
			<li><a href="http://pgoh13.com/budapest.php" rel="nofollow">Budapest</a></li>
			<li><a href="http://pgoh13.com/paris_page1.php" rel="nofollow">Paris</a></li>
			<li><a href="http://pgoh13.com/rome.php" rel="nofollow">Rome</a></li>
			<li><a href="http://pgoh13.com/london.php" rel="nofollow">London</a></li>
			<li><a href="http://pgoh13.com/barcelona.php" rel="nofollow">Barcelona</a></li>
			<li><a href="http://pgoh13.com/madrid/" rel="nofollow">Madrid</a></li>
			<li><a href="http://pgoh13.com/venice.php" rel="nofollow">Venice</a></li>
			<li><a href="http://pgoh13.com/prague.php" rel="nofollow">Prague</a></li>
			<li><a href="http://pgoh13.com/amsterdam.php" rel="nofollow">Amsterdam</a></li>
			<li><a href="http://pgoh13.com/athens.php" rel="nofollow">Athens</a></li>
			<li><a href="http://pgoh13.com/copenhagen.php" rel="nofollow">Copenhagen</a></li>
			<li><a href="http://pgoh13.com/geneva.php" rel="nofollow">Geneva</a></li>
			<li><a href="http://pgoh13.com/andalucia.php" rel="nofollow">Andalucia</a></li>
			<li><a href="http://pgoh13.com/french_riviera.php" rel="nofollow">French Riviera</a></li>
			
		</ul></li>
		<li><a href="http://pgoh13.com/china.php" rel="nofollow"><span>China</span></a>
		<ul>
			<li><a href="http://pgoh13.com/zhouzhuang.php" rel="nofollow">Zhouzhuang</a></li>
			<li><a href="http://pgoh13.com/hangzhou.php" rel="nofollow">Hangzhou</a></li>
			<li><a href="http://pgoh13.com/xian.php" rel="nofollow">Xian</a></li>
			<li><a href="http://pgoh13.com/shanghai1.php" rel="nofollow">Shanghai</a></li>
			<li><a href="http://pgoh13.com/beijing_introduction.php" rel="nofollow">Beijing</a></li>
		</ul></li>
		<li><a href="http://pgoh13.com/Malaysia_new.php" rel="nofollow"><span>Malaysia/Singapore</span></a>
		<ul>
			<li><a href="http://pgoh13.com/visit_perhentian.php" rel="nofollow">Perhentian Islands</a></li>
			<li><a href="http://pgoh13.com/visit_cameron.php" rel="nofollow">Cameron Highlands</a></li>
			<li><a href="http://pgoh13.com/visit_kb.php" rel="nofollow">Kota Bharu</a></li>
			<li><a href="http://pgoh13.com/visit_melaka.php" rel="nofollow">Malacca</a></li>
			<li><a href="http://pgoh13.com/visit_penang1.php" rel="nofollow">Penang</a></li>
			<li><a href="http://pgoh13.com/visit_kl.php" rel="nofollow">Kuala Lumpur</a></li>
			<li><a href="http://pgoh13.com/singapore.php" rel="nofollow">Singapore</a></li>
		</ul></li>
		<li><a href="http://pgoh13.com/morocco.php" rel="nofollow"><span>Morocco</span></a>
		<ul>
			<li><a href="http://pgoh13.com/agadir.php" rel="nofollow">Agadir</a></li>
			<li><a href="http://pgoh13.com/rabat.php" rel="nofollow">Rabat</a></li>
			<li><a href="http://pgoh13.com/casablanca.php" rel="nofollow">Casablanca</a></li>
			<li><a href="http://pgoh13.com/marrakesh.php" rel="nofollow">Marrakesh</a></li>
		</ul></li>
	
<li><a href="http://www.worldtravelguide.net" rel="nofollow" target="_blank">World destinations</a></li>
	</ul></li>


	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>SONGS</span></a>
	<ul>

		<li><a href="http://pgoh13.com/softsongs/" rel="nofollow" target="_blank">40 relaxing songs non-stop</a></li>
		<li><a href="http://pgoh13.com/mobile/" rel="nofollow" target="_blank">English Songs and Their Lyrics</a></li>
		<li><a href="http://pgoh13.com/m.frenchsongsandlyrics.php" rel="nofollow" target="_blank">Popular French songs</a></li>
		<li><a href="http://pgoh13.com/malaysongs/" rel="nofollow" target="_blank">Malay Songs</a></li>
		<li><a href="http://pgoh13.com/spanishsongs/" rel="nofollow" target="_blank">Spanish Songs</a></li>
		<li><a href="http://pgoh13.com/chinese_songs.php" rel="nofollow" target="_blank">Chinese songs</a></li>
		<li><a href="http://pgoh13.com/deezer/" rel="nofollow" target="_blank">Deezer playlists</a></li>
		<li><a href="http://pgoh13.com/oldsongs_newsingers.php" rel="nofollow" target="_blank">Old songs, new singers</a></li>
		<li><a href="http://pgoh13.com/songs/" rel="nofollow" target="_blank" title="Evergreens/Oldies" class=white>Evergreens/Oldies</a></li>
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>LANGUAGES</span></a>
	<ul>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-french" rel="nofollow" target=_blank>French-English-French dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-spanish" rel="nofollow" target=_blank>Spanish-English-Spanish dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-german" rel="nofollow" target=_blank>German-English-German dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-italian" rel="nofollow" target=_blank>Italian-English-Italian dictionary</a></li>
		<li><a href=http://www.mdbg.net/chindict/chindict.php rel="nofollow" target=_blank>English to Chinese dictionary</a></li>
		<li><a href=http://www.linguee.com/ rel="nofollow" target=_blank>Linguee French, Spanish, German dictionary for phrases</a></li>
		<li><a href=http://ukdataexplorer.com/european-translator/ rel="nofollow" target=_blank>European Word Translator by James Trimber</a></li>
		<li><a href=http://www.lingvozone.com/ rel="nofollow" target=_blank>Multi-lingual dictionary with pronunciation</a></li>
		<li><a href="http://pgoh13.com/mycourse/" rel="nofollow" target=_blank>Malaysian and Indonesian languages</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_introduction.php" rel="nofollow">Chinese Pinyin Lessons</a></li>
		<li><a href="http://dictionary.pgoh13.com/" rel="nofollow">English-Malay Dictionary</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_characters.php" rel="nofollow">Basic Chinese Characters</a></li>
<li><a href="http://www.word2word.com/course.html" rel="nofollow" target="_blank">All World Languages</a></li>
		
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>INFO</span></a>
	<ul>
	<li><a href="http://pgoh13.com/calendar2017.html" rel="nofollow">2017 Calendar/Events</a></li>
	<li><a href="http://www.web-l.com/country-codes/" rel="nofollow" target="_blank">Country codes for internet</a></li>
	<li><a href="http://onlineconversion.com/" rel="nofollow" target="_blank">Conversions (length, weight, volume, temperature)</a></li>
	<li><a href="http://wwp.greenwichmeantime.com/time-zone/usa/eastern-time/convert/index.htm" rel="nofollow" target="_blank">Time Conversion:  EST to GMT</a></li>
	<li><a href="http://www.urbanrail.net/" rel="nofollow" target="_blank">World subways/metro</a></li>		
	<li><a href="http://www.infobel.com/world/default.asp" rel="nofollow" target="_blank">World telephone directories</a></li>
	<li><a href="http://embassyinformation.com/" rel="nofollow" target="_blank">World Embassies</a></li>
	<li><a href="http://www.journeymart.com/tools/world-holidays/default.aspx" rel="nofollow" target="_blank">World public holidays</a></li>
	<li><a href="http://www.seat61.com/" rel="nofollow" target="_blank">World train time-tables</a></li>
	<li><a href="http://www.timeanddate.com/worldclock/dialing.html" rel="nofollow" target="_blank">International Dialling Codes</a></li>
	<li><a href="http://www.timeanddate.com/date/weekday.html" rel="nofollow" target="_blank">What day is this date?</a></li>		
	</ul></li>
	
	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>INTERNET</span></a>
	<ul>
		<li><a href="http://pgoh13.com/control_button.php" rel="nofollow">The Ctrl button</a></li>
		<li><a href="http://pgoh13.com/software_progs1.php" rel="nofollow">Useful programs</a></li>
		<li><a href="http://pgoh13.com/internet_tips1.php" rel="nofollow">Internet/Computer tips</a></li>
		<li><a href="http://pgoh13.com/using_hola.php" rel="nofollow">Using Hola! to access blocked sites</a></li>
		<li><a href="http://pgoh13.com/using_printedit.php" rel="nofollow">Using Print Edit</a></li>
		<li><a href="http://pgoh13.com/using_spybot.php" rel="nofollow">Using Spybot</a></li>
		<li><a href="http://pgoh13.com/using_pixlr_masked.php" rel="nofollow">Using PIXLR</a></li>
		<li><a href="http://pgoh13.com/using_manageflitter.php" rel="nofollow">Using ManageFlitter</a></li>
		<li><a href="http://pgoh13.com/using_teamviewer.php" rel="nofollow">Using TeamViewer</a></li>
		<li><a href="http://pgoh13.com/using_partitionwizard.php" rel="nofollow">Using Partition Wizard</a></li>
		<li><a href="http://pgoh13.com/cobian_backup.php" rel="nofollow">Using Cobian Backup</a></li>
		<li><a href="http://pgoh13.com/rssreader_installation.php" rel="nofollow">Using the RssReader</a></li>
		<li><a href="http://pgoh13.com/copy_youtube.php" rel="nofollow">Tips for YouTube</a></li>
		<li><a href="http://pgoh13.com/spam_list.php" rel="nofollow">Email spams and scams</a></li>
		<li><a href="http://pgoh13.com/special_characters.php" rel="nofollow">Special characters</a></li>
		<li><a href="http://pgoh13.com/country_domains.php" rel="nofollow">Country domain initials</a></li>
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>LEISURE</span></a>
	<ul>
		<li><a href="http://pgoh13.com/justforlaughs.php" rel="nofollow">Just for laughs</a></li>
		<li><a href="http://pgoh13.com/brainteasers.php" rel="nofollow">Brainteasers</a></li>
		<li><a href="http://pgoh13.com/quotations.php" rel="nofollow">Inspiring quotations</a></li>
		<li><a href="http://pgoh13.com/pensioners_page.php" rel="nofollow">Page for senior citizens</a></li>
		<li><a href="http://pgoh13.com/ecard_quotes.php" rel="nofollow">Motivational e-cards</a></li>
</ul></li>

<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>NEWS</span></a>
	<ul>
<li><a href="http://www.bbc.com/" rel="nofollow" target="_blank">BBC (News headlines)</a></li>
<li><a href="http://edition.cnn.com/WORLD/" rel="nofollow" target="_blank">CNN World News</a></li>
<li><a href="http://www.aljazeera.com/" rel="nofollow" target="_blank">Al Jazeera News</a></li>
<li><a href="http://www.huffingtonpost.com/?country=US" rel="nofollow" target="_blank">Huffington Post US</a></li>
<li><a href="http://www.huffingtonpost.co.uk/" rel="nofollow" target="_blank">Huffington Post UK</a></li>
<li><a href="http://www.newsy.com/categories/world/" rel="nofollow" target="_blank">News from Newsy.com</a></li> 
<li><a href="http://www.buzzfeed.com/" rel="nofollow" target="_blank">BuzzFeed</a></li>
<li><a href="http://www.thedailybeast.com/" rel="nofollow" target="_blank">The Daily Beast</a></li>
<li><a href="http://www.newsweek.com/en" rel="nofollow" target="_blank">Newsweek</a></li>
<li><a href="http://www.slate.com/" rel="nofollow" target="_blank">Slate magazine</a></li>
<li><a href="http://mashable.com/" rel="nofollow" target="_blank">Mashable</a></li>
<li><a href="http://pgoh13.com/4news_agencies.html" rel="nofollow" target="_blank">International news agencies</a></li> 
<li><a href="http://youtube-trends.blogspot.com/" rel="nofollow" target="_blank">YouTube trends</a></li> 
<li><a href="http://www.tmz.com" rel="nofollow" target="_blank">TMZ entertainment news</a></li>
</ul></li>



	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>SPORTS</span></a>
	<ul>
		<li><a href="http://www.rugbyworldcup.com/" rel="nofollow" target="_blank">Rugby</a></li>
		<li><a href="http://www.fifa.com" rel="nofollow" target="_blank">Football (FIFA)</a></li>
		<li><a href="http://pgoh13.com/20kms.php" rel="nofollow" target="_blank">Jogging/Marathons</a></li>
		<li><a href="http://www.bwfbadminton.org/" rel="nofollow" target="_blank">Badminton (BWF)</a></li>
		<li><a href="http://www.fiba.com/" rel="nofollow" target="_blank">Basketball (FIBA)</a></li>
		<li><a href="http://www.itftennis.com/home.aspx" rel="nofollow" target="_blank">Tennis (ITF)</a></li>
		<li><a href="http://www.igfgolf.org/" rel="nofollow" target="_blank">Golf (IGF)</a></li>
		<li><a href="http://www.iaaf.org/home" rel="nofollow" target="_blank">World Athletics (IAAF)</a></li>
		<li><a href="http://www.fina.org/H2O/" rel="nofollow" target="_blank">Swimming (FINA)</a></li>
		<li><a href="http://www.nfl.com/" rel="nofollow" target="_blank">American Football (NFL)</a></li>
		<li><a href="http://www.icc.cricket.org" rel="nofollow" target="_blank">Cricket (ICC)</a></li>
		</ul></li>




<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>HEALTH</span></a>
	<ul>
		<li><a href="http://pgoh13.com/health_page.php" rel="nofollow">Common health issues and topics</a></li>
		<li><a href="http://pgoh13.com/health_problems.php" rel="nofollow">Layman's guide to diseases</a></li>
	</ul></li>



<li class="topmenu"><a href="http://pgoh13.com/recipes_page.php" rel="nofollow" style="height:18px;line-height:18px;">FOOD</a></li>


<li class="topmenu"><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" rel="nofollow" target="_blank" style="height:18px;line-height:18px;">CONTACT</a></li>


<li class="toplast"><a href="http://pgoh13.com/about_pgoh13.php" rel="nofollow" target="_blank" style="height:18px;line-height:18px;">ABOUT</a></li>



</ul>
</nav>



<table border="0"><tbody><tr>
<td>
<!-- Search Google -->
<span style="font-family:arial;font-size:0.9em;">Type your search query here:</span>&nbsp;<img src=google_icon.jpg height=20><br>
<FORM method=GET action="http://www.google.com/search" target=_blank>
<TABLE bgcolor="#FFFFFF" cellspacing=0 border=0><tr><td>
<INPUT TYPE=text id=mytext name=q size=30 maxlength=255 value="">
<INPUT TYPE=hidden name=hl value="en">
<INPUT type=submit name=btnG VALUE="Google Search">
</td></tr></TABLE>
</FORM>
<!-- Search Google -->
</td>
<td width=20></td>
<td>&nbsp;&nbsp;If you find this site interesting or useful, do share it with your friends!<br>
<? include "imagemap.inc";  ?>
</td>

</tr></tbody></table>

</center>


<!-- FreeFind End No Index -->
<!-- End css3menu.com BODY section -->