<p>
<section>
<!-- Search Google -->
<span style="font-family:arial;font-size:0.9em;">Type your search query here:</span>&nbsp;<img src=google_icon.jpg height=20><br>
<FORM method=GET action="http://www.google.com/search" target=_blank>
<TABLE bgcolor="#FFFFFF" cellspacing=0 border=0><tr><td>
<INPUT TYPE=text id=mytext name=q size=30 maxlength=255 value="">
<INPUT TYPE=hidden name=hl value="en">
<INPUT type=submit name=btnG VALUE="Google Search">
</td></tr></TABLE>
</FORM>
<!-- Search Google -->
</section>
</p>

<p>
<section>
<p>If you find this site interesting or useful, do share it with your friends!<br>
<? include "imagemap.inc";  ?>
</section>
</p>
