<? include "nav.inc"; ?>

<head>
<title>French Songs with their lyrics</title>
<meta name="description" content="The Best-Known French Songs of All Time (and some lesser-known ones) with their lyrics.  This is only a personal list.  You are entitled to your own!" />
</head>

<h1>French Songs with their lyrics</h1>

<p><a href="http://pgoh13.com/mobile/amsterdam-jacques-brel/">Amsterdam (Jacques Brel)
    </a><br><a href="http://pgoh13.com/mobile/avec-le-temps-leo-ferre/">Avec le temps (Léo Ferré)
    </a><br><a href="http://pgoh13.com/mobile/belle-from-notre-dame-de-paris/">Belle (from Notre-Dame de Paris)
    </a><br><a href="http://pgoh13.com/mobile/belle-ile-en-mer-laurent-voulzy/">Belle-ile-en-mer (Laurent Voulzy)
    </a><br><a href="http://pgoh13.com/mobile/bonjour-tristesse-juliette-greco/">Bonjour tristesse (Juliette Gréco)
    </a><br><a href="http://pgoh13.com/mobile/capri-cest-fini-herve-vilard/">Capri c'est fini (Hervé Vilard)
    </a><br><a href="http://pgoh13.com/mobile/cecile-ma-fille-claude-nougaro/">Cécile ma fille (Claude Nougaro)
    </a><br><a href="http://pgoh13.com/mobile/chanson-pour-lauvergnat-georges-brassens/">Chanson pour l'Auvergnat (Georges Brassens)
    </a><br><a href="http://pgoh13.com/mobile/comme-dhabitude-claude-francois/">Comme d'habitude (Claude François)
    </a><br><a href="http://pgoh13.com/mobile/comme-ils-disent-charles-aznavour/">Comme ils disent (Charles Aznavour)
    </a><br><a href="http://pgoh13.com/mobile/comment-te-dire-adieu-francoise-hardy/">Comment te dire adieu? (Françoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/des-que-le-vent-soufflera-renaud/">Dès que le vent soufflera (Renaud)
    </a><br><a href="http://pgoh13.com/mobile/dis-quand-reviendras-tu-barbara/">Dis, quand reviendras-tu? (Barbara)
    </a><br><a href="http://pgoh13.com/mobile/douce-france-charles-trenet/">Douce France (Charles Trenet)
    </a><br><a href="http://pgoh13.com/mobile/elle-est-dailleurs-pierre-bachelet/">Elle est d'ailleurs (Pierre Bachelet)
    </a><br><a href="http://pgoh13.com/mobile/en-chantant-michel-sardou/">En chantant (Michel Sardou)
    </a><br><a href="http://pgoh13.com/mobile/et-meme-francoise-hardy/">Et même (Françoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/et-maintenant-gilbert-becaud/">Et maintenant (Gilbert Bécaud)
    </a><br><a href="http://pgoh13.com/mobile/et-si-tu-nexistais-pas-joe-dassin/">Et si tu n'existais pas (Joe Dassin)
    </a><br><a href="http://pgoh13.com/mobile/etretat-pierre-bachelet/">Etretat (Pierre Bachelet)
    </a><br><a href="http://pgoh13.com/mobile/harley-davidson-brigitte-bardot/">Harley Davidson (Brigitte Bardot)
    </a><br><a href="http://pgoh13.com/mobile/hier-encore-charles-aznavour/">Hier encore (Charles Aznavour)
    </a><br><a href="http://pgoh13.com/mobile/hymne-a-lamour-edith-piaf/">Hymne à l'amour (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/il-est-5h-paris-seveille-jacques-dutronc/">Il est 5h, Paris s'éveille (Jacques Dutronc)
    </a><br><a href="http://pgoh13.com/mobile/il-me-dit-que-je-suis-belle-patricia-kaas/">Il me dit que je suis belle (Patricia Kaas)
    </a><br><a href="http://pgoh13.com/mobile/il-ny-a-pas-damour-heureux-francoise-hardy/">Il n'y a pas d'amour heureux (Francoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/il-ny-a-plus-dapres-juliette-greco/">Il n'y a plus d'après (Juliette Gréco)
    </a><br><a href="http://pgoh13.com/mobile/il-suffirait-de-presque-rien-serge-reggiani/">Il suffirait de presque rien (Serge Reggiani)
    </a><br><a href="http://pgoh13.com/mobile/jattendrai-dalida/">J'attendrai (Dalida)
    </a><br><a href="http://pgoh13.com/mobile/je-laime-a-mourir-francis-cabrel/">Je l'aime à mourir (Francis Cabrel)
    </a><br><a href="http://pgoh13.com/mobile/je-mvoyais-dj-charles-aznavour/">Je m'voyais déjà (Charles Aznavour)
    </a><br><a href="http://pgoh13.com/mobile/je-ne-regrette-rien-edith-piaf/">Je ne regrette rien (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/je-suis-malade-serge-lama/">Je suis malade (Serge Lama)
    </a><br><a href="http://pgoh13.com/mobile/je-suis-venu-te-dire-que-je-men-vais-serge-gainsbourg/">Je suis venu te dire que je m'en vais (Serge Gainsbourg)
    </a><br><a href="http://pgoh13.com/mobile/je-taime-moi-non-plus-jane-birkin-et-serge-gainsbourg/">Je t'aime, moi non plus (Jane Birkin et Serge Gainsbourg)
    </a><br><a href="http://pgoh13.com/mobile/je-te-donne-jean-jacques-goldman/">Je te donne (Jean-Jacques Goldman)
    </a><br><a href="http://pgoh13.com/mobile/je-te-promets-johnny-halliday/">Je te promets (Johnny Halliday)
    </a><br><a href="http://pgoh13.com/mobile/je-vais-taimer-michel-sardou/">Je vais t'aimer (Michel Sardou)
    </a><br><a href="http://pgoh13.com/mobile/jolie-mome-leo-ferre/">Jolie mome (Léo Ferré)
    </a><br><a href="http://pgoh13.com/mobile/laigle-noir-barbara/">L'aigle noir (Barbara)
    </a><br><a href="http://pgoh13.com/mobile/lencre-de-tes-yeux-francis-cabrel/">L'encre de tes yeux (Francis Cabrel)
    </a><br><a href="http://pgoh13.com/mobile/la-boheme-charles-aznavour/">La bohème (Charles Aznavour)
    </a><br><a href="http://pgoh13.com/mobile/la-chanson-de-prevert-serge-gainsbourg/">La chanson de Prévert (Serge Gainsbourg)
    </a><br><a href="http://pgoh13.com/mobile/la-chanson-des-vieux-amants-juliette-greco/">La chanson des vieux amants (Juliette Gréco)
    </a><br><a href="http://pgoh13.com/mobile/la-foule-edith-piaf/">La foule (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/la-java-bleue-frehel/">La java bleue (Fréhel)
    </a><br><a href="http://pgoh13.com/mobile/la-javanaise-serge-gainsbourg/">La Javanaise (Serge Gainsbourg)
    </a><br><a href="http://pgoh13.com/mobile/la-maladie-damour-michel-sardou/">La maladie d'amour (Michel Sardou)
    </a><br><a href="http://pgoh13.com/mobile/la-maritza-sylvie-vartan/">La Maritza (Sylvie Vartan)
    </a><br><a href="http://pgoh13.com/mobile/la-memoire-et-la-mer-leo-ferre/">La mémoire et la mer (Léo Ferré)
    </a><br><a href="http://pgoh13.com/mobile/la-mer-charles-trenet/">La mer (Charles Trenet)
    </a><br><a href="http://pgoh13.com/mobile/la-montagne-jean-ferrat/">La montagne (Jean Ferrat)
    </a><br><a href="http://pgoh13.com/mobile/la-plus-belle-pour-aller-danser-sylvie-vartan/">La plus belle pour aller danser (Sylvie Vartan)
    </a><br><a href="http://pgoh13.com/mobile/la-romance-de-paris-charles-trenet/">La romance de Paris (Charles Trenet)
    </a><br><a href="http://pgoh13.com/mobile/clips-video-et-les-paroles-des-chansons-francaises/">La vie en rose (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/le-plat-pays-jacques-brel/">Le plat pays (Jacques Brel)
    
    </a><br><a href="http://pgoh13.com/mobile/le-temps-de-lamour-francoise-hardy/">Le temps de l'amour (Françoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/le-temps-des-cerises-yves-montand/">Le temps des cerises (Yves Montand)
    </a><br><a href="http://pgoh13.com/mobile/le-tourbillon-jeanne-moreau/">Le tourbillon (Jeanne Moreau)
    </a><br><a href="http://pgoh13.com/mobile/le-vent-nous-portera-noir-desir/">Le vent nous portera (Noir Desir)
    </a><br><a href="http://pgoh13.com/mobile/les-amants-dun-jour-edith-piaf/">Les amants d'un jour (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/les-amoureux-des-bancs-publics-georges-brassens/">Les amoureux des bancs publics (Georges Brassens)
    </a><br><a href="http://pgoh13.com/mobile/les-copains-dabord-georges-brassens/">Les copains d'abord (Georges Brassens)
    </a><br><a href="http://pgoh13.com/mobile/les-corons-pierre-bachelet/">Les corons (Pierre Bachelet)
    </a><br><a href="http://pgoh13.com/mobile/les-couleurs-du-temps-guy-beart/">Les couleurs du temps (Guy Béart)
    </a><br><a href="http://pgoh13.com/mobile/les-feuilles-mortes-yves-montand/">Les feuilles mortes (Yves Montand)
    </a><br><a href="http://pgoh13.com/mobile/les-mots-bleus-christophe/">Les mots bleus (Christophe)
    </a><br><a href="http://pgoh13.com/mobile/les-moulins-de-mon-coeur-michel-legrand/">Les moulins de mon coeur (Michel Legrand)
    </a><br><a href="http://pgoh13.com/mobile/lucie-pascal-obispo/">Lucie (Pascal Obispo)
    </a><br><a href="http://pgoh13.com/mobile/mnilmontant-charles-trenet/">Ménilmontant (Charles Trenet)
    </a><br><a href="http://pgoh13.com/mobile/ma-plus-belle-histoire-damour-barbara/">Ma plus belle histoire d'amour (Barbara)
    
    </a><br><a href="http://pgoh13.com/mobile/milord-edith-piaf/">Milord (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/mistral-gagnant-renaud/">Mistral gagnant (Renaud)
    </a><br><a href="http://pgoh13.com/mobile/mon-amant-de-saint-jean-lucienne-delyle/">Mon amant de Saint Jean (Lucienne Delyle)
    </a><br><a href="http://pgoh13.com/mobile/mon-amie-la-rose-francoise-hardy/">Mon amie la rose (Françoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/ne-me-quitte-pas-jacques-brel/">Ne me quitte pas (Jacques Brel)
    </a><br><a href="http://pgoh13.com/mobile/padam-padam-edith-piaf/">Padam Padam (Edith Piaf)
    </a><br><a href="http://pgoh13.com/mobile/quand-on-na-que-lamour-jacques-brel/">Quand on n'a que l'amour (Jacques Brel)
    </a><br><a href="http://pgoh13.com/mobile/que-je-taime-johnny-hallyday/">Que je t'aime (Johnny Hallyday)
    </a><br><a href="http://pgoh13.com/mobile/que-reste-t-il-de-nos-amours-charles-trenet/">Que reste-t-il de nos amours (Charles Trenet)
    
    </a><br><a href="http://pgoh13.com/mobile/qui-a-le-droit-patrick-bruel/">Qui a le droit (Patrick Bruel)
    </a><br><a href="http://pgoh13.com/mobile/qui-saura-mike-brant/">Qui saura (Mike Brant)
    </a><br><a href="http://pgoh13.com/mobile/savoir-aimer-florent-pagny/">Savoir aimer (Florent Pagny)
    </a><br><a href="http://pgoh13.com/mobile/she-charles-aznavour/">She (Charles Aznavour)
    </a><br><a href="http://pgoh13.com/mobile/sous-le-ciel-de-paris-juliette-greco/">Sous le ciel de Paris (Juliette Gréco)
    
    </a><br><a href="http://pgoh13.com/mobile/tous-les-garcons-et-les-filles-francoise-hardy/">Tous les garçons et les filles (Françoise Hardy)
    </a><br><a href="http://pgoh13.com/mobile/un-gamin-de-paris-yves-montand/">Un gamin de Paris (Yves Montand)
    </a><br><a href="http://pgoh13.com/mobile/une-belle-histoire-michel-fugain/">Une belle histoire (Michel Fugain)

</p>


<? include "nav2.inc"; ?>