<html><head>
<link rel="shortcut icon" href="http://pgoh13.com/favicon.ico">
<p><table align=left valign=top><tr><td valign=top>
<!--  without the above line doesn't work as there are tables below this table  -->

<!-- Below script is to receive adsense data in google analytics -->
<script type="text/javascript">
window.google_analytics_uacct = "UA-4651027-1";
</script>

<style>
.gray {color:gray}
.green {color:green}
.lightgreen {color:lightgreen}
.darkorange {color:darkorange}
.orange {color:yellow}
.blue {color:blue}
.red {color:red}
.white {color:white}
.silver {color:silver}
.yellow1 {color:#FFFC17}
.darkpurple {color:darkpurple}
.black {color:black}
.midnightblue {color:midnightblue}
.malayword {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
.yellow {font-family: "century gothic"; color: red; font-size:18px}
.yellow2 {color:yellow}
.inmalay {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
</style>

<STYLE TYPE="text/css">
<!--
 .al { text-align : justify; font-family : verdana,arial,times}
 A:hover {background:yellow; color : blue}
A {text-decoration:none }
-->
</STYLE>

<script language="JavaScript">
function focusIt(ele)
{
ele.focus();
}
</script>
<?/* above script replaces this one
<script type="text/javascript">
  function setfocus()
  {
    document.forms[0].q.focus()
  }
  </script> */?>

<script type="text/javascript">
function mailto(domain,user) 
{ 
document.location.href = "mailto:" + user + "@" + domain;
}
</script>

<style type="text/css">
table.pleasenote2 {
border-color: darkblue; border-width:0; border-style:solid;
margin: 5px}
table.pleasenote2 td {
font: bold 10pt verdana, arial, sans-serif;
color:yellow; background-color:black}
table.heading td {
font: bold 20pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote3 td {text-align:left;
font: normal 8pt verdana, arial, sans-serif;
color:red; background-color:yellow; border-style:solid;
	border-width:1px;
	border-color:black;} 
table.heading td {
font: bold 12pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote4 {
border-color: darkblue; border-width:2; border-style:solid;
margin: 2px}
table.pleasenote4 td {
font: normal 12pt verdana, arial, sans-serif;
color:midnightblue; background-color:beige} 
table.heading td {
font: bold 32pt verdana, arial, sans-serif;
color:red; background-color:yellow}
</style>
<style type="text/css">
h1 {	font-family:"Arial";
	font-size: 30px;
	color:yellow;
	text-align:center;	
   }
h2 {	font-family:"Arial";
	font-size: 24px;
	color:yellow;
	text-align:center;	
   }
h3 {	font-family:"Arial";
	font-size: 18px;
	color:#00FF00;
	text-align:center;	
   }
</style>

<script
 src="http://onlinecount.com/onnow.php?site=ss03536"
language="javascript" type="text/javascript">
</script>

<style type="text/css">
.typeface {font-family:tahoma;
font-size: 16px;
font-weight:bold;}
</style>

</head>
<body bgcolor="#cccccc" onload="focusIt(document.forms.q)">

<!-- google_ad_section_start(weight=ignore) -->

<table width=180><tr><td width="100%" bgcolor=black><font face=arial size=2>
<style type="text/css">
@import url(http://www.google.com/cse/api/branding.css);
</style>
<div class="cse-branding-right" style="background-color:#660000;color:#FFFFFF">
  <div class="cse-branding-form">
    <form action="http://pgoh13.com/google_searchresults.php" id="cse-search-box">
      <div>
        <input type="hidden" name="cx" value="partner-pub-3250339308164521:5f4c5h-ah8o" />
        <input type="hidden" name="cof" value="FORID:10" />
        <input type="hidden" name="ie" value="ISO-8859-1" />
        <input type="text" name="q" size="23" />
		<div class="cse-branding-logo"><img 		src="http://www.google.com/images/poweredby_transparent/poweredby_000000.gif" 		alt="Google" />
        <input type="submit" name="sa" value="Search" />
      </div>
    </form>
  </div>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black><font face=arial size=2>
<b><a href="webmail.php" title="Read your emails from here!" class=white>Go everywhere from here</a>
<br><A href="2011_calendar.php" title="2011 Calendar"  class=red target=_blank>2011 Calendar/Events</a>
<br><A href="allthenews.php" title="News at a glance"  class=white target=_blank>Today's news at a glance</a>
<br><A href="search4sites.php" title="Check 4 search engines at one go!" class=white>Six search engines</a>
<br><A href="timeat_aglance.php" title="Real-time clocks in major cities" class=white>Exact time in ...</a>
<br><A href="medical_page.php" title="Medical/Health issues" class=white>Health/Medical issues</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="copy_youtube.php" title="How to copy YouTube clips to your hard disk" class=white>Copying from YouTube</a>
<br><A href="internet_tips1.php" title="Getting the most out of Internet" class=white>Internet/Computer tips</a>
<br><A href="software_progs1.php" title="Free and useful software to install" class=white>Useful software</a>
<br><A href="software_list.php" title="List of indispensable programs to download" class=white>Programs to download</a>
<br><a href="http://www.easytobook.com/?amu=280822023" target="_blank" title="Online hotel reservations" class=white>Online hotel reservations</a>
<?/*  
<br><A href="porkbelly_dish.php" title="Recipe for another variety of tau yu bak" class=white><b>What's cooking?</a>
<br><A href="http://tinyurl.com/58b2yd" title="Songs of yesteryears from YouTube" class=white><b>Memories are made of this</a>
<br><a href="advertising_info.php" title="Advertising information"><b style="padding:0px; color:black; background:#00FF00;display:block;">Note to advertisers</b></a>
 */?>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2> 
<b><A href="visiting_europe.php" title="Visiting Europe's top cities"  class=white target=_blank>Visiting Europe</a>
<br><A href="visiting_china.php" title="Visiting China"  class=white target=_blank>Visiting China</a>
<br><A href="morocco.php" title="Visiting Morocco"  class=white target=_blank>Visiting Morocco</a>
<br><A href="Malaysia.php" title="Focus on Malaysia"  class=white target=_blank>Focus on Malaysia</a>
<br><A href="http://pgoh13.com/" title="The world at your fingertips"  class=white target=_blank>HOME</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://bgoh.free.fr/deezer" title="Songs from deezer.com" class=white target="_blank"><b>Songs from deezer.com</a>
<br><A href="http://tinyurl.com/6yrmv9" title="Non-stop English songs" class=white target="_blank"><b>Non-stop English songs</a>
<br><A href="http://tinyurl.com/5wsyff" title="Non-stop French songs" class=white target="_blank"><b>Non-stop French songs</a>
<br><A href="http://tinyurl.com/2th7po" title="Lyrics of evergreens and oldies" class=white target="_blank">Lyrics of evergreens</a>
<br><A href="oldsongs_newsingers.php" title="Old songs by new singers" class=white><b>Old songs new singers</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="brainteasers.php" title="Brainteasers 1" class=white>Brainteasers 1</a>
<br><A href="quotations.php" title="Inspiring quotations and ideas" class=white>Inspiring quotes/ideas</a>
<br><A href="ecard_quotes.php" title="Motivational or inspirational cards" class=white>Motivational e-cards</a>
<br><A href="justforlaughs.php" title="No kidding: this is the world's funniest joke"  class=white>Just for laughs</a>
<br><A href="essays.php" title="Articles that set you thinking" class=white target=_blank>Opinion/Essays</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pinyin.pgoh13.com/" title="Learn to speak Chinese"  class=white target=_blank>Learn Chinese pinyin</a>
<br><A href="http://pinyin.pgoh13.com/chinese_characters.php" title="Chinese characters in pinyin" class=white>Chinese characters</a>
<br><A href="chinese_songs.php" title="Popular Chinese songs"  class=white target=_blank>Popular Chinese songs</a>
<br><A href="fifa_worldcup.php" title="2010 FIFA World Cup results" class=white>Full World Cup results</a>
<br><A href="expo_shanghai.php" title="Shanghai Expo 2010" class=white>Shanghai Expo 2010</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=1>
<b><a href="javascript:mailto('laposte.net','p.goh')" class=white>Contact/Feedback</a>
<br><a href=privacy_policy.php  class=white target=_blank>Privacy policy</a>
<br><a href=about_thissite.php  class=white target=_blank>About this site</a>
</b>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="wantto_sudoku.php" title="First steps with Sudoku" class=white>Sudoku for all</a>
<br><A href="spam_list.php" title="Tips for a spam-free email" class=white>How to fight spam</a>
<br><A href="win7.php" title="What's new in Windows 7"  class=white target=_blank>What's new in Windows 7</a>
<br><A href="http://www.elite.net/~runner/jennifers/" title="Hello in all languages" class=white target=_blank><b>Hello in all languages</a>
<br /><A href="special_characters.php" title="How to type special characters" class=white><b>Special characters</a>
<br><A href="http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains" title="Domains by country" class=white target=_blank><b>Domains by country</a>
<br><a href="http://searchcrm.techtarget.com/sDefinition/0,,sid11_gci211776,00.html" title="Chat lingo" class=white target=_blank>Chat lingo</a>
<br><A href="http://whatis.techtarget.com/file-extension-list-A/0,289933,sid9,00.html" title="File extension list" class=white target=_blank><b>File extension list</a>
</td></tr></table>

<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=5774811; 
var sc_invisible=1; 
var sc_security="330a1a19"; 
</script>

<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="tumblr site counter"
href="http://www.statcounter.com/tumblr/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/5774811/0/330a1a19/1/"
alt="tumblr site counter" ></a></div></noscript>
<!-- End of StatCounter Code -->

</td></tr></table>

<object 
    type="text/x-scriptlet" width=1 height=1 
    data="http://www.onlinecount.com/trak.php?site=ss03536"> 
  </object>

</td></tr></table valign=bottom>
<!-- google_ad_section_end(weight=ignore) -->
<!-- google_ad_section_start -->


<p><table width="180" align="right" valign="top"><tr><td>
<script type="text/javascript"><!--
google_ad_client = "pub-3250339308164521";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_ad_type = "text_image";
//2007-09-18: 120by600adsonrightsideofpage
google_ad_channel = "6611182558";
google_color_border = "cccccc";
google_color_bg = "cccccc";
google_color_link = "000000";
google_color_text = "000000";
google_color_url = "000000";
google_ui_features = "rc:6";
//-->
</script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<br />
<script type="text/javascript"><!--
google_ad_client = "pub-3250339308164521";
/* 180x150_updated, created 10/30/10 */
google_ad_slot = "5163101152";
google_ad_width = 180;
google_ad_height = 150;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>


</td></tr></table>


<!-- google_ad_section_end(weight=ignore) -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-4651027-4', 'auto');
  ga('send', 'pageview');
</script>

<!-- google_ad_section_start -->
