<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"> <!-- The majority of the world uses UTF-8 for just about everything nowadays -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<script>
function setFocusToTextBox(){
    document.getElementById("mytext").focus();
}
</script>

<!-- without the js code below the dropdown menu won't work -->
<script>
$(document).ready( function() {
$('.dropdown-toggle').dropdown();
});
</script>

<style>
.navbar-inverse .navbar-nav li a:hover {
	background: #27A967;}
</style>

</head>

<body style="background-color:#cccccc;">
<nav class="navbar navbar-inverse">
  <div class="container-fluid"> <!-- this part stretches width to fill whole monitor -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
<span style="color:white;font-size:10px">MENU</span>                      
      </button>
      <a class="navbar-brand" style="background-color:red;color:black;" href="http://pgoh13.com">World Fingertips&nbsp;<span class="glyphicon glyphicon-home glyphicon-large" aria-hidden="true"></span></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
            <li class="active"><a href="http://pgoh13.com">Home</a></li>
            
 <li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">TRAVEL<span class="caret"></span></a>
                <ul class="dropdown-menu">
          <li><a href="http://pgoh13.com/bruges.html" rel="nofollow">Bruges</a></li>
                <li><a href="http://pgoh13.com/krakow.php" rel="nofollow">Krakow</a></li>
		<li><a href="http://pgoh13.com/riga.php" rel="nofollow">Riga</a></li>
		<li><a href="http://pgoh13.com/berlin.php" rel="nofollow">Berlin</a></li>
		<li><a href="http://pgoh13.com/milan.php" rel="nofollow">Milan</a></li>	
		<li><a href="http://pgoh13.com/lisbon.php" rel="nofollow">Lisbon</a></li>
			<li><a href="http://pgoh13.com/dublin.php" rel="nofollow">Dublin</a></li>
			<li><a href="http://pgoh13.com/sicily" rel="nofollow">Sicily</a></li>
			<li><a href="http://pgoh13.com/budapest.php" rel="nofollow">Budapest</a></li>
			<li><a href="http://pgoh13.com/paris_page1.php" rel="nofollow">Paris</a></li>
			<li><a href="http://pgoh13.com/rome.php" rel="nofollow">Rome</a></li>
			<li><a href="http://pgoh13.com/london.php" rel="nofollow">London</a></li>
			<li><a href="http://pgoh13.com/barcelona.php" rel="nofollow">Barcelona</a></li>
			<li><a href="http://pgoh13.com/madrid/" rel="nofollow">Madrid</a></li>
			<li><a href="http://pgoh13.com/venice.php" rel="nofollow">Venice</a></li>
			<li><a href="http://pgoh13.com/prague.php" rel="nofollow">Prague</a></li>
			<li><a href="http://pgoh13.com/amsterdam.php" rel="nofollow">Amsterdam</a></li>
			<li><a href="http://pgoh13.com/athens.php" rel="nofollow">Athens</a></li>
			<li><a href="http://pgoh13.com/copenhagen.php" rel="nofollow">Copenhagen</a></li>
			<li><a href="http://pgoh13.com/geneva.php" rel="nofollow">Geneva</a></li>
			<li><a href="http://pgoh13.com/andalucia.php" rel="nofollow">Andalucia</a></li>
			<li><a href="http://pgoh13.com/french_riviera.php" rel="nofollow">French Riviera</a></li>
<li><a href="http://pgoh13.com/china.php" rel="nofollow">China</a></li>
<li><a href="http://pgoh13.com/malaysia_new.php" rel="nofollow">Malaysia</a></li>
<li><a href="http://pgoh13.com/morocco.php" rel="nofollow">Morocco</a></li>
</ul>

            
 <li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SONGS<span class="caret"></span></a>
                <ul class="dropdown-menu">
		<li><a href="http://pgoh13.com/top10.html" rel="nofollow" target="_blank">This week's Top 10</a></li>
		<li><a href="http://pgoh13.com/softsongs/" rel="nofollow" target="_blank">40 relaxing songs non-stop</a></li>
		<li><a href="http://pgoh13.com/mobile/" rel="nofollow" target="_blank">English Songs and Their Lyrics</a></li>
		<li><a href="http://pgoh13.com/malaysongs/" rel="nofollow" target="_blank">Malay Songs</a></li>
		<li><a href="http://pgoh13.com/spanishsongs/" rel="nofollow" target="_blank">Spanish Songs</a></li>
		<li><a href="http://pgoh13.com/chinese_songs.php" rel="nofollow" target="_blank">Chinese songs</a></li>
		<li><a href="http://pgoh13.com/deezer/" rel="nofollow" target="_blank">Deezer playlists</a></li>
		<li><a href="http://pgoh13.com/oldsongs_newsingers.php" rel="nofollow" target="_blank">Old songs, new singers</a></li>
		<li><a href="http://pgoh13.com/songs/" rel="nofollow" target="_blank">Evergreens/Oldies</a></li>          	
</ul>


 <li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">INFO<span class="caret"></span></a>
                <ul class="dropdown-menu">
	<li class="active"><a href="http://pgoh13.com/calendar2017.html" rel="nofollow">2017 Calendar/Events</a></li>
	<li><a href="http://www.web-l.com/country-codes/" rel="nofollow" target="_blank">Country codes for internet</a></li>
	<li><a href="http://onlineconversion.com/" rel="nofollow" target="_blank">Conversions (length, weight, volume, temperature)</a></li>
	<li><a href="http://wwp.greenwichmeantime.com/time-zone/usa/eastern-time/convert/index.htm" rel="nofollow" target="_blank">Time Conversion:  EST to GMT</a></li>
	<li><a href="http://www.urbanrail.net/" rel="nofollow" target="_blank">World subways/metro</a></li>		
	<li><a href="http://www.infobel.com/world/default.asp" rel="nofollow" target="_blank">World telephone directories</a></li>
	<li><a href="http://embassyinformation.com/" rel="nofollow" target="_blank">World Embassies</a></li>
	<li><a href="http://www.journeymart.com/tools/world-holidays/default.aspx" rel="nofollow" target="_blank">World public holidays</a></li>
	<li><a href="http://www.seat61.com/" rel="nofollow" target="_blank">World train time-tables</a></li>
	<li><a href="http://www.timeanddate.com/worldclock/dialing.html" rel="nofollow" target="_blank">International Dialling Codes</a></li>
	<li><a href="http://www.timeanddate.com/date/weekday.html" rel="nofollow" target="_blank">What day is this date?</a></li>		</ul>

 <li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">INTERNET<span class="caret"></span></a>
                <ul class="dropdown-menu">
		<li class="active"><a href="http://pgoh13.com/control_button.php" rel="nofollow">The Ctrl button</a></li>
		<li><a href="http://pgoh13.com/software_progs1.php" rel="nofollow">Useful programs</a></li>
		<li><a href="http://pgoh13.com/internet_tips1.php" rel="nofollow">Internet/Computer tips</a></li>
		<li><a href="http://pgoh13.com/using_hola.php" rel="nofollow">Using Hola! to access blocked sites</a></li>
		<li><a href="http://pgoh13.com/using_printedit.php" rel="nofollow">Using Print Edit</a></li>
		<li><a href="http://pgoh13.com/using_spybot.php" rel="nofollow">Using Spybot</a></li>
		<li><a href="http://pgoh13.com/using_pixlr_masked.php" rel="nofollow">Using PIXLR</a></li>
		<li><a href="http://pgoh13.com/using_manageflitter.php" rel="nofollow">Using ManageFlitter</a></li>
		<li><a href="http://pgoh13.com/using_teamviewer.php" rel="nofollow">Using TeamViewer</a></li>
		<li><a href="http://pgoh13.com/using_partitionwizard.php" rel="nofollow">Using Partition Wizard</a></li>
		<li><a href="http://pgoh13.com/cobian_backup.php" rel="nofollow">Using Cobian Backup</a></li>
		<li><a href="http://pgoh13.com/rssreader_installation.php" rel="nofollow">Using the RssReader</a></li>
		<li><a href="http://pgoh13.com/copy_youtube.php" rel="nofollow">Tips for YouTube</a></li>
		<li><a href="http://pgoh13.com/spam_list.php" rel="nofollow">Email spams and scams</a></li>
		<li><a href="http://pgoh13.com/special_characters.php" rel="nofollow">Special characters</a></li>
		<li><a href="http://pgoh13.com/country_domains.php" rel="nofollow">Country domain initials</a></li>
	</ul>

<li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LANGUAGES<span class="caret"></span></a>
<ul class="dropdown-menu">
		<li class="active"><a href="http://www.collinsdictionary.com/dictionary/english-french" rel="nofollow" target=_blank>French-English-French dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-spanish" rel="nofollow" target=_blank>Spanish-English-Spanish dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-german" rel="nofollow" target=_blank>German-English-German dictionary</a></li>
		<li><a href="http://www.collinsdictionary.com/dictionary/english-italian" rel="nofollow" target=_blank>Italian-English-Italian dictionary</a></li>
		<li><a href=http://www.mdbg.net/chindict/chindict.php rel="nofollow" target=_blank>English to Chinese dictionary</a></li>
		<li><a href=http://www.linguee.com/ rel="nofollow" target=_blank>Linguee French, Spanish, German dictionary for phrases</a></li>
		<li><a href=http://ukdataexplorer.com/european-translator/ rel="nofollow" target=_blank>European Word Translator by James Trimber</a></li>
		<li><a href=http://www.lingvozone.com/ rel="nofollow" target=_blank>Multi-lingual dictionary with pronunciation</a></li>
		<li><a href="http://pgoh13.com/mycourse/" rel="nofollow" target=_blank>Malaysian and Indonesian languages</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_introduction.php" rel="nofollow">Chinese Pinyin Lessons</a></li>
		<li><a href="http://dictionary.pgoh13.com/" rel="nofollow">English-Malay Dictionary</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_characters.php" rel="nofollow">Basic Chinese Characters</a></li>
<li><a href="http://www.word2word.com/course.html" rel="nofollow" target="_blank">All World Languages</a></li>
</ul>


<li class="dropdown">        
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LEISURE<span class="caret"></span></a>
<ul class="dropdown-menu">
		<li class="active"><a href="http://pgoh13.com/justforlaughs.php" rel="nofollow">Just for laughs</a></li>
		<li><a href="http://pgoh13.com/brainteasers.php" rel="nofollow">Brainteasers</a></li>
		<li><a href="http://pgoh13.com/quotations.php" rel="nofollow">Inspiring quotations</a></li>
		<li><a href="http://pgoh13.com/pensioners_page.php" rel="nofollow">Page for senior citizens</a></li>
		<li><a href="http://pgoh13.com/ecard_quotes.php" rel="nofollow">Motivational e-cards</a></li>
		<li><a href="http://pgoh13.com/health_problems.php" rel="nofollow">Layman's guide to diseases</a></li>
</ul>

<li><a href="http://pgoh13.com/about_pgoh13.php" target="_blank">About</a></li>
<li><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" target="_blank">Contact</a></li>
</ul>

 <ul class="nav navbar-nav navbar-right"><br>

                  <form name="google-search" method="get" action="http://www.google.com/search">
<button type="submit" class="btn btn-default btn-sm">
<span class="glyphicon glyphicon-search glyphicon-large" aria-hidden="true"> </span>
</button>
      <input type="hidden" name="sitesearch" value="http://pgoh13.com/" />
      <input name="q" type="text" />
      <input type="submit" name="sa" value="Search this site" />
</form>
              </ul>

    </div>
  </div>
</nav>
