<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- asynchronous_code -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-3250339308164521"
     data-ad-slot="3375394129"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br />
<script type="text/javascript"><!--
google_ad_client = "pub-3250339308164521";
/* 728x15, created 9/10/11 */
google_ad_slot = "0182079722";
google_ad_width = 728;
google_ad_height = 15;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<br />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- asynchronous_code -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-3250339308164521"
     data-ad-slot="3375394129"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br />
