
<style type="text/css">
a {text-decoration: none;}
a:hover {color:green;font-weight:bolder;}
</style>
<div style="width:900px;background-color:beige;margin-left:20px;margin-top:10px;font-family:arial;font-size:12px;font-weight:bold;border:1px solid black;padding:10px;text-align:left;"><strong>TRAVEL.  Places covered in this website: </strong>&nbsp;

<A href=http://pgoh13.com/krakow.php target=_blank>Krakow</a> | 
<A href=http://pgoh13.com/riga.php target=_blank>Riga</a> | 
<A href=http://pgoh13.com/berlin.php target=_blank>Berlin</a> | 
<A href=http://pgoh13.com/milan.php target=_blank>Milan</a> | 
<A href=http://pgoh13.com/lisbon.php target=_blank>Lisbon</a> | 
<A href=http://pgoh13.com/dublin.php target=_blank>Dublin</a> | 
<A href=http://pgoh13.com/sicily/>Sicily</a> | 
<A href=http://pgoh13.com/budapest.php target=_blank>Budapest</a> | 
<A href=http://pgoh13.com/venice.php target=_blank>Venice</a> | 
<A href=http://pgoh13.com/paris_page1.php target=_blank>Paris</a> | 
<A href=http://pgoh13.com/madrid/ target=_blank>Madrid</a> | 
<A href=http://pgoh13.com/london.php target=_blank>London</a> | 
<A href=http://pgoh13.com/barcelona.php target=_blank>Barcelona</a> | 
<A href=http://pgoh13.com/rome.php target=_blank>Rome</a> | 
<A href=http://pgoh13.com/naples.php target=_blank>Naples</a> | 
<A href=http://pgoh13.com/french_riviera.php target=_blank>Cannes</a> | 
<A href=http://pgoh13.com/french_riviera3.php target=_blank>Monaco</a> | 
<A href=http://pgoh13.com/french_riviera2.php target=_blank>Nice</a> | 
<A href=http://pgoh13.com/geneva.php target=_blank>Geneva</a> | 
<A href=http://pgoh13.com/amsterdam.php target=_blank>Amsterdam</a> | 
<A href=http://pgoh13.com/beijing_introduction.php target=_blank>Beijing</a> | 
<A href=http://pgoh13.com/shanghai1.php target=_blank>Shanghai</a> | 
<A href=http://pgoh13.com/xian.php target=_blank>Xi'an</a> | 
<A href=http://pgoh13.com/hangzhou.php target=_blank>Hangzhou</a> | 
<A href=http://pgoh13.com/marrakesh.php target=_blank>Marrakesh</a> | 
<A href=http://pgoh13.com/casablanca.php target=_blank>Casablanca</a> | 
<A href=http://pgoh13.com/visit_penang.php target=_blank>Penang</a> | 
<A href=http://pgoh13.com/visit_kl.php target=_blank>Kuala Lumpur</a> | 
<A href=http://pgoh13.com/visit_melaka.php target=_blank>Malacca</a> | 
<A href=http://pgoh13.com/capri.php target=_blank>Capri Island</a> | 
<A href=http://pgoh13.com/copenhagen.php target=_blank>Copenhagen</a> | 
<A href=http://pgoh13.com/malmo.php target=_blank>Malmo</a> | 
<A href=http://pgoh13.com/singapore.php target=_blank>Singapore</a> | 
<A href=http://pgoh13.com/visit_perhentian.php target=_blank>Perhentian Islands</a> | 
<A href=http://pgoh13.com/larochelle_intro.php target=_blank>La Rochelle</a> | 
<A href=http://pgoh13.com/ile_dere.php target=_blank>Ile de R&eacute;</a> | 
<A href=http://pgoh13.com/madrid/toledo.php target=_blank>Toledo</a> | 
<A href=http://pgoh13.com/brighton_visit.php target=_blank>Brighton</a> | 
<A href=http://pgoh13.com/oslo.php target=_blank>Oslo</a> | 
<a href=http://pgoh13.com/athens.php target=_blank>Athens</a> | 
<a href=http://pgoh13.com/andalucia.php target=_blank>Andalucia</a> | 
<A href=http://pgoh13.com/prague.php target=_blank>Prague</a> | 
<A href=http://pgoh13.com/rouen.php target=_blank>Rouen</a> | 
<A href=http://pgoh13.com/kent/ target=_blank>Kent</a>
</div>
