<html><head>
<link rel="shortcut icon" href="http://pgoh13.com/favicon.ico"> 
<table align=left valign=top><tr><td valign=top>
<!--  without the above line doesn't work as there are tables below this table  -->

<style>
.gray {color:gray}
.green {color:green}
.lightgreen {color:lightgreen}
.darkorange {color:darkorange}
.orange {color:yellow}
.blue {color:blue}
.red {color:red}
.white {color:white}
.silver {color:silver}
.yellow1 {color:#FFFC17}
.darkpurple {color:darkpurple}
.black {color:black}
.midnightblue {color:midnightblue}
.malayword {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
.yellow {font-family: "century gothic"; color: red; font-size:18px}
.yellow2 {color:yellow}
.inmalay {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
</style>

<STYLE TYPE="text/css">
<!--
 .al { text-align : justify; font-family : verdana,arial,times}
 A:hover {background:yellow; color : blue}
A {text-decoration:none }
-->
</STYLE>

<script language="JavaScript">
function focusIt(ele)
{
ele.focus();
}
</script>
<?/* above script replaces this one
<script type="text/javascript">
  function setfocus()
  {
    document.forms[0].q.focus()
  }
  </script> */?>

<script type="text/javascript">
function mailto(domain,user) 
{ 
document.location.href = "mailto:" + user + "@" + domain;
}
</script>

<style type="text/css">
table.pleasenote2 {
border-color: darkblue; border-width:0; border-style:solid;
margin: 5px}
table.pleasenote2 td {
font: bold 10pt verdana, arial, sans-serif;
color:yellow; background-color:black}
table.heading td {
font: bold 20pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote3 td {text-align:left;
font: normal 8pt verdana, arial, sans-serif;
color:red; background-color:yellow; border-style:solid;
	border-width:1px;
	border-color:black;} 
table.heading td {
font: bold 12pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote4 {
border-color: darkblue; border-width:2; border-style:solid;
margin: 2px}
table.pleasenote4 td {
font: normal 12pt verdana, arial, sans-serif;
color:midnightblue; background-color:beige} 
table.heading td {
font: bold 32pt verdana, arial, sans-serif;
color:red; background-color:yellow}
</style>
<style type="text/css">
h1 {	font-family:"Arial";
	font-size: 30px;
	color:yellow;
	text-align:center;	
   }
h2 {	font-family:"Arial";
	font-size: 24px;
	color:yellow;
	text-align:center;	
   }
h3 {	font-family:"Arial";
	font-size: 18px;
	color:#00FF00;
	text-align:center;	
   }
</style>

<style type="text/css">
.typeface {font-family:tahoma;
font-size: 16px;
font-weight:bold;}
</style>

</head>
<body bgcolor="#cccccc" onload="focusIt(document.forms.q)">

<table width=180 align=left><tr><td>
<!-- google_ad_section_start(weight=ignore) -->

<table width=180><tr><td width="100%" bgcolor=#cccccc><font face=arial size=2><b>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a href="http://www.addthis.com/bookmark.php?v=250&amp;username=xa-4d2831f668a4ac9f" class="addthis_button_compact">Share</a>
<span class="addthis_separator">|</span>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=xa-4d2831f668a4ac9f"></script>
<!-- AddThis Button END -->

</td></tr></table>
<br />

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/dictionary.php" title="English-Malay Dictionary" class=white>English-Malay Dictionary</a>
<br /><A href="http://malay.pgoh13.com/" title="Malay language course" class=white>Malay language course</a>
<br /><A href="http://malay.pgoh13.com/malay_sentences.php" title="Today's Malay sentence" class=white>Today's Malay sentence(s)</a>
<br /><A href="http://pinyin.pgoh13.com/" title="Learn to speak Chinese"  class=white target=_blank>Learn Chinese pinyin</a>
<br /><A href="http://pgoh13.com/worlds_myhome.php" title="The World's My Home"  class=white target=_blank>The World's My Home</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/visiting_europe.php" title="Visiting Europe's top cities"  class=white target=_blank>Visiting Europe</a>
<br /><A href="http://pgoh13.com/visiting_china.php" title="Visiting China"  class=white target=_blank>Visiting China</a>
<br /><A href="http://pgoh13.com/morocco.php" title="Visiting Morocco"  class=white target=_blank>Visiting Morocco</a>
<br /><A href="http://pgoh13.com/Malaysia.php" title="Focus on Malaysia"  class=white target=_blank>Visiting Malaysia</a>
<br /><A href="http://pgoh13.com/" title="The world at your fingertips"  class=white target=_blank>HOME</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=http://feeds.feedburner.com/RssFeedsFromPgoh13com title="RSS feeds" target=_blank><img src=http://pgoh13.com/rss.gif><img src=http://pgoh13.com/rss2.gif></a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/copy_youtube.php" title="How to copy YouTube clips to your hard disk" class=white>Useful tips for YouTube</a>
<br /><A href="http://pgoh13.com/cobian_backup.php" title="Using Cobian Backup" class=white>Using Cobian Backup</a>
<br /><A href="http://pgoh13.com/internet_tips1.php" title="Getting the most out of Internet" class=white>Internet/Computer tips</a>
<br /><A href="http://pgoh13.com/software_progs1.php" title="Free and useful software to install" class=white>Useful software</a>
<br /><A href="http://pgoh13.com/quotations.php" title="Inspiring quotations and ideas" class=white>Inspiring quotes/ideas</a>
<br /><A href="http://pgoh13.com/brainteasers.php" title="Brainteasers 1" class=white>Brainteasers</a>
<br /><A href="http://pgoh13.com/justforlaughs.php" title="No kidding: this is the world's funniest joke"  class=white>Just for laughs</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/spam_list.php" title="Tips for a spam-free email" class=white>How to fight spam</a>
<br /><A href="http://pgoh13.com/special_characters.php" title="How to type special characters" class=white><b>Special characters</a>
<br><A href="http://pgoh13.com/search4sites.php" title="Check 4 search engines at one go!" class=white>Six search engines</a>
<br /><A href="http://pgoh13.com/win7.php" title="What's new in Windows 7"  class=white target=_blank>What's new in Windows 7</a>
<br /><a href="http://www.easytobook.com/?amu=280822023" target="_blank" title="Online hotel reservations" class=white>Online hotel reservations</a>
<br /><A href="http://pinyin.pgoh13.com/chinese_characters.php" title="Chinese characters" class=white><b>Chinese characters</a>
<br /><A href="http://pgoh13.com/chinese_songs.php" title="Chinese songs" class=white><b>Chinese songs</a>
<br /><A href="http://pgoh13.com/oldsongs_newsingers.php" title="Old songs new singers" class=white><b>Old songs new singers</a>
<br /><A href="http://pgoh13.com/deezer/" title="Deezer playlists" class=white><b>Deezer playlists</a>
<br /><A href="http://bgoh.free.fr/lyrics/" title="Song lyrics" class=white><b>Song lyrics</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=1>
<b><a href="javascript:mailto('pgoh13.com','webmaster')" title="Contact/Feedback" class=white>Contact/Feedback</a>
<br /><a href="http://pgoh13.com/about_us.php" title="About us"  class=white target=_blank>About us</a>
<br /><a href="http://pgoh13.com/sitemap.html" title="Sitemap"  class=white target=_blank>Sitemap</a>
<br /><a href="http://pgoh13.com/privacy_policy.php" title="Privacy policy"  class=white target=_blank>Privacy policy</a>
</b></td></tr></table>

<br />
<script type="text/javascript"><!--
google_ad_client = "pub-3250339308164521";
/* 160x600_with_image, created 9/1/10 */
google_ad_slot = "4225195233";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

</td></tr></table>

<!-- google_ad_section_start -->