<html><head>
<link rel="shortcut icon" href="http://pgoh13.com/favicon.ico" rel="nofollow"> 

<script language="javascript" type="text/javascript" src="http://pgoh13.com/scripts/jquery.js"></script>
            <script language="javascript" type="text/javascript">$.noConflict();</script>
            <script language="javascript" type="text/javascript" src="http://pgoh13.com/scripts/doubleclick.js"></script>


<style>
.gray {color:gray}
.green {color:green}
.lightgreen {color:lightgreen}
.darkorange {color:darkorange}
.orange {color:yellow}
.blue {color:blue}
.red {color:red}
.white {color:white}
.silver {color:silver}
.yellow1 {color:#FFFC17}
.darkpurple {color:darkpurple}
.black {color:black}
.midnightblue {color:midnightblue}
.malayword {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
.yellow {font-family: "century gothic"; color: red; font-size:18px}
.yellow2 {color:yellow}
.inmalay {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
</style>

<STYLE TYPE="text/css">
<!--
 .al { text-align : justify; font-family : verdana,arial,times}
 A:hover {background:yellow; color : blue}
A {text-decoration:none }
-->
</STYLE>

<script language="JavaScript">
function focusIt(ele)
{
ele.focus();
}
</script>
<?/* above script replaces this one
<script type="text/javascript">
  function setfocus()
  {
    document.forms[0].q.focus()
  }
  </script>
<font size=1>
<br /><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" rel="nofollow" title="Contact Form" target="_blank" class=white>Email/Contact/Feedback</a>
<br /><a href="http://pgoh13.com/about_us.php" rel="nofollow" title="About"  class=white target=_blank>About us</a>
 */?>

<script type="text/javascript">
function mailto(domain,user) 
{ 
document.location.href = "mailto:" + user + "@" + domain;
}
</script>

<style type="text/css">
table.pleasenote2 {
border-color: darkblue; border-width:0; border-style:solid;
margin: 5px}
table.pleasenote2 td {
font: bold 10pt verdana, arial, sans-serif;
color:yellow; background-color:black}
table.heading td {
font: bold 20pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote3 td {text-align:left;
font: normal 8pt verdana, arial, sans-serif;
color:red; background-color:yellow; border-style:solid;
	border-width:1px;
	border-color:black;} 
table.heading td {
font: bold 12pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote4 {
border-color: darkblue; border-width:2; border-style:solid;
margin: 2px}
table.pleasenote4 td {
font: normal 12pt verdana, arial, sans-serif;
color:midnightblue; background-color:beige} 
table.heading td {
font: bold 32pt verdana, arial, sans-serif;
color:red; background-color:yellow}
</style>
<style type="text/css">
h1 {	font-family:"Arial";
	font-size: 30px;
	color:yellow;
	text-align:center;	
   }
h2 {	font-family:"Arial";
	font-size: 24px;
	color:yellow;
	text-align:center;	
   }
h3 {	font-family:"Arial";
	font-size: 18px;
	color:#00FF00;
	text-align:center;	
   }
</style>

<style type="text/css">
.typeface {font-family:tahoma;
font-size: 16px;
font-weight:bold;}
</style>
</head>

<body bgcolor=#cccccc onload="setupDoubleClick('http://www.macmillandictionary.com/', 'british', null, false, null);">


<div id="google_translate_element"></div><script>
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en',
    autoDisplay: false,
    layout: google.translate.TranslateElement.InlineLayout.SIMPLE
  }, 'google_translate_element');
}
</script><script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/" rel="nofollow" title="The world at your fingertips"  class=white target=_blank>Home Page</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=http://feeds.feedburner.com/RssFeedsFromPgoh13com rel="nofollow" title="RSS feeds" target=_blank><img src=http://pgoh13.com/rss_combined.gif rel="nofollow"></a>
<br /><a href="http://pgoh13.com/francais" rel="nofollow" target=_blank class=white>En fran&ccedil;ais &nbsp;<img src=flag_french.gif></a>
<br /><a href="http://pgoh13.com/2013_calendar.php" rel="nofollow" title="2013 Calendar and Events" class=white>2013 Calendar/Events</a>
<br /><a href="http://pgoh13.com/fifa_worldcup2014.php" rel="nofollow" title="2014 FIFA World Cup" class=white>2014 FIFA World Cup</a>
<br /><a href="http://pgoh13.com/timeat_aglance.php" rel="nofollow" class=white>Get exact time</a>
<br /><a href="http://www.timeanddate.com/weather/" rel="nofollow" target=_blank class=white>Get present weather</a>
<br /><a href="http://pgoh13.com/converter_xe.php" rel="nofollow" target=_blank class=white>Your money converter</a>
<br />
<a href="http://pgoh13.com/location_address.php" rel="nofollow" target=_blank class=white>Type address for map:</a>
<form name="location" action="http://maps.google.co.uk/maps" method="get" target="_blank">
<input type="text" size="15" maxlength="255" name="saddr" id="saddr" value="" />
<input type="submit" value="GO" />
</form>
<br />
<form method="get" target="_blank" action="http://dictionary.reference.com/search">
<table width="170" border="0" cellspacing="4" cellpadding="4" bgcolor="#000000">
<tr>
<td valign="middle" align="left">
<span style="font-family: arial,helvetica,sans-serif; font-size: 100%; color: #ffffff;">English dictionary:</span>
<input type="text" name="q" size="10" maxlength="50" style="font-size:11pt;">
<input type="submit" value="GO" style="font-weight:normal; font-size:11pt; font-family: arial,helvetica,sans-serif;">
</td>
</tr>
</table>
</form>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://translate.google.com/" rel="nofollow" title="Anything to translate?"  class=white target=_blank>Anything to translate?</a>
<br /><a href="http://pgoh13.com/site_index.html" rel="nofollow" title="Sitemap of The World At Your Fingertips"  class=white target=_blank>Sitemap (Index to site)</a>
<br /><A href="http://pgoh13.com/worlds_myhome.php" rel="nofollow" title="The World's My Home"  class=white target=_blank>The World's My Home</a>
<br /><A href="http://pgoh13.com/europe.php" rel="nofollow" title="Visiting Europe's top cities"  class=white target=_blank>Visiting Europe</a>
<br /><A href="http://pgoh13.com/china.php" rel="nofollow" title="Visiting China"  class=white target=_blank>Visiting China</a>
<br /><A href="http://pgoh13.com/morocco.php" rel="nofollow" title="Visiting Morocco"  class=white target=_blank>Visiting Morocco</a>
<br /><A href="http://pgoh13.com/Malaysia_new.php" rel="nofollow" title="Visiting Malaysia"  class=white target=_blank>Visiting Malaysia</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pgoh13.com/copy_youtube.php" rel="nofollow" title="How to copy YouTube clips to your hard disk" class=white>Useful tips for YouTube</a>
<br /><A href="http://pgoh13.com/password_creating.php" rel="nofollow" title="How to create your own password" class=white>Your own password</a>
<br /><A href="http://pgoh13.com/rssreader_installation.php" rel="nofollow" title="Using RssReader" class=white>Using RssReader</a>
<br /><A href="http://pgoh13.com/cobian_backup.php" rel="nofollow" title="Using Cobian Backup" class=white>Using Cobian Backup</a>
<br /><A href="http://pgoh13.com/internet_tips1.php" rel="nofollow" title="Getting the most out of Internet" class=white>Internet/Computer tips</a>
<br /><A href="http://pgoh13.com/software_progs1.php" rel="nofollow" title="Free and useful software to install" class=white>Useful software</a>
<br /><A href="http://pgoh13.com/quotations.php" rel="nofollow" title="Inspiring quotations and ideas" class=white>Inspiring quotes/ideas</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://pgoh13.com/health_page.php" rel="nofollow" title="Health topics" class=white>Health topics</a>
<br /><a href="http://pgoh13.com/recipes_page.php" rel="nofollow" title="Food recipes" class=white>Food recipes</a>
<br /><a href="http://pgoh13.com/brainteasers.php" rel="nofollow" title="Brainteasers 1" class=white>Brainteasers</a>
<br /><A href="http://pgoh13.com/justforlaughs.php" rel="nofollow" title="No kidding: this is the world's funniest joke"  class=white>Just for laughs</a>
<br /><a href="http://pgoh13.com/pensioners_page.php" rel="nofollow" class=white>Page for senior citizens</a>
<br /><A href="http://pgoh13.com/spam_list.php" rel="nofollow" title="Email spams and scams" class=white>Email spams and scams</a>
<br /><A href="http://pgoh13.com/special_characters.php" rel="nofollow" title="How to type special characters" class=white>Those special characters</a>
<br><A href="http://pgoh13.com/search4sites.php" rel="nofollow" title="Check 4 search engines at one go!" class=white>Six search engines</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://pgoh13.com/oldsongs_newsingers.php" rel="nofollow" title="Old songs new singers" class=white>Old songs new singers</a>
<br /><A href="http://pgoh13.com/deezer/" rel="nofollow" title="Deezer playlists" class=white>Deezer playlists</a>
<br /><a href="http://pgoh13.com/greatest_french_songs.php" target="_blank" title="The greatest French songs of all time" class=white>Greatest French songs</a>
<br /><a href="http://pgoh13.com/greatest_english_songs.php" target="_blank" title="List of 700 English songs in Songs and Lyrics" class=white>700 English songs</a>
<br /><A href="http://pgoh13.com/chinese_songs.php" rel="nofollow" title="Chinese songs" class=white>Chinese songs</a>
<br /><A href="http://pgoh13.com/malaysongs/" rel="nofollow" title="Malay songs" class=white>Malay songs</a>
<br /><A href="http://pgoh13.com/spanishsongs/" rel="nofollow" title="Spanish songs" class=white>Spanish songs</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pinyin.pgoh13.com/chinese_introduction.php" rel="nofollow" title="Learn to speak Chinese"  class=white target=_blank>Learn Chinese pinyin</a>
<br /><A href="http://pinyin.pgoh13.com/chinese_characters.php" rel="nofollow" title="Chinese characters" class=white>Chinese characters</a>
<br /><A href="http://dictionary.pgoh13.com/" rel="nofollow" title="English-Malay Dictionary" class=white>English-Malay Dictionary</a>
<br /><A href="http://malay.pgoh13.com/" rel="nofollow" title="Malay language course" class=white>Malay language course</a>
<br /><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" rel="nofollow" class="white" target=_blank>Contact &nbsp;<img src=http://pgoh13.com/envelope.gif></a>
<br /><a href="http://pgoh13.com/about_pgoh13.php" class="white" target="_blank">About</a>

</b></td></tr></table>

<? 
/* <br>
<div id="clustrmaps-widget"></div><script type="text/javascript">var _clustrmaps = {'url' : 'http://pgoh13.com/', 'user' : 868601, 'server' : '2', 'id' : 'clustrmaps-widget', 'version' : 1, 'date' : '2012-12-12', 'lang' : 'en', 'corners' : 'square' };(function (){ var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = 'http://www2.clustrmaps.com/counter/map.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);})();</script><noscript><a href="http://www2.clustrmaps.com/user/e65d40f9" target="_blank"><img src="http://www2.clustrmaps.com/stats/maps-no_clusters/pgoh13.com--thumb.jpg" alt="Locations of visitors to this page" /></a></noscript>

<!-- Site Meter -->
<script type="text/javascript" src="http://s26.sitemeter.com/js/counter.js?site=s26focusmalaysia" target="_blank">
</script>
<noscript>
<a href="http://s26.sitemeter.com/stats.asp?site=s26focusmalaysia" target="_blank">
<img src="http://s26.sitemeter.com/meter.asp?site=s26focusmalaysia" alt="Site Meter" border="0"/></a>
</noscript>
<!-- Copyright (c)2009 Site Meter -->

<a href="http://www.xiti.com/xiti.asp?s=363353" title="WebAnalytics" target="_top">
<script type="text/javascript">
<!--
Xt_param = 's=363353&p=';
try {Xt_r = top.document.referrer;}
catch(e) {Xt_r = document.referrer; }
Xt_h = new Date();
Xt_i = '<img width="10" height="2" border="0" alt="" ';
Xt_i += 'src="http://logv3.xiti.com/hit.xiti?'+Xt_param;
Xt_i += '&hl='+Xt_h.getHours()+'x'+Xt_h.getMinutes()+'x'+Xt_h.getSeconds();
if(parseFloat(navigator.appVersion)>=4)
{Xt_s=screen;Xt_i+='&r='+Xt_s.width+'x'+Xt_s.height+'x'+Xt_s.pixelDepth+'x'+Xt_s.colorDepth;}
document.write(Xt_i+'&ref='+Xt_r.replace(/[<>"]/g, '').replace(/&/g, '$')+'" title="Internet Audience">');
//-->
</script>
<noscript>
Mesure d'audience ROI statistique webanalytics par <img width="39" height="25" src="http://logv3.xiti.com/hit.xiti?s=363353&p=" alt="WebAnalytics" />
</noscript></a>
*/ ?>

<!-- google_ad_section_end(weight=ignore) -->
<!-- google_ad_section_start -->
