<!-- google_ad_section_start -->
<table><tr><td bgcolor="#CCFF99"><font face="Arial" size="2"><b>A basic course in Bahasa Malaysia (or Malaysian language - originally Malay language) &nbsp;<span style="font-size:smaller; color:black; font-weight:bolder; "><b> &copy;GPJ</b></span></b></td>
</tr><tr><td bgcolor=orange><font face=Arial size=2 color=white><b><a href="http://pgoh13.com/amazon_malaylanguage.html" rel="nofollow" target="_blank">Books on Bahasa Malaysia.</a></td>
</tr><tr><td bgcolor=midnightblue><font face=Arial size=2 color=white><b>These lessons are copyrighted and their publication in any form is strictly prohibited.</td>
</tr></table>

<? /*
$today = date("w");
$hari = array(
"</tr><tr><td bgcolor=yellow><font face=Arial size=2><b>To stop the audio file go to the bottom of the page and click on the tiny square button.</td>",
"</tr><tr><td bgcolor=red><font face=Arial size=2 color=yellow><b>Those in a hurry need only study the few model sentences in the top table of each lesson by heart.</td>", 
"</tr><tr><td bgcolor=orange><font face=Arial size=2><b>
This course is completely free because I believe Internet is all about sharing.</td>",
"</tr><tr><td bgcolor=black><font face=Arial size=2 color=yellow><b>Old students please note that additions have been made to quite a number of lessons.</td>",
"</tr><tr><td bgcolor=midnightblue><font face=Arial size=2 color=white><b>To search for a Malay word just type it in the Search this site box (at bottom of the left frame).</td>",
"</tr><tr><td bgcolor=yellow><font face=Arial size=2><b>This course will also be useful to anyone studying the Indonesian language (Bahasa Indonesia).</td>", 
"</tr><tr><td bgcolor=orange><font face=Arial size=2><b>This course is meant to be studied over a period of six months. Don't try to do it in one day!</td>");
print("$hari[$today]");
 */ ?>
