<head>
<style type="text/css">
.typeface {font-family:Verdana;
font-size: 18px;}

table.answerbox {
	border-width: 1px;
	border-spacing: ;
	border-style: normal;
	border-color: red;
	border-collapse: collapse;
	background-color: red;
border-spacing:3;
margin: 2px;
border:1px solid black;
}
table.answerbox th {
font-family:Arial;
font-size: 1em;
color:midnightblue;
	border-width: 1px;
	padding: 5px;
	
	border-color: red;
	background-color: yellow;
	-moz-border-radius: ;
border:1px solid black;
}
table.answerbox td {color:black;
font-family:Verdana;
font-size: 1em;
	border-width: 1px;
	padding: 5px;
	font-weight:normal;
	border-color: red;
	background-color: beige;
	-moz-border-radius: ;
border:1px solid black;
}
</style>

</head>


<body>
<table style="border-style:hidden;"><tr>
<td>
<b><a style="text-decoration:none;color:#00009C" href="table_contentsPC.htm" rel="nofollow">Table of Lessons (for PC)</a> &nbsp; | &nbsp;
<a style="text-decoration:none;color:#00009C" href=http://pgoh13.free.fr/>HOME PAGE</a>
</td></tr></table>
<table style="border:0;padding:0;margin:0;"><tr>
<td bgcolor="yellow"><font face="Arial" size="2"><b>A basic course in the Malaysian and Indonesian languages in 64 lessons &nbsp;&copy;pgoh</b></td>
</tr><tr>
<td bgcolor=midnightblue><font face=Arial size=2 color=white><b>This version is to be used on a desktop.  Smartphone users <a style="text-decoration:none;color:#00009C" href=index.htm><font color=yellow> go here.</font></a>
</td></tr></table>

