<head>
<style type="text/css">
.typeface {font-family:Verdana;
font-size: 18px;}

table.answerbox {
	border-width: 1px;
	border-spacing: ;
	border-style: normal;
	border-color: red;
	border-collapse: collapse;
	background-color: red;
border-spacing:3;
margin: 2px;
border:1px solid black;
}
table.answerbox th {
font-family:Arial;
font-size: 1em;
color:midnightblue;
	border-width: 1px;
	padding: 5px;
	
	border-color: red;
	background-color: yellow;
	-moz-border-radius: ;
border:1px solid black;
}
table.answerbox td {color:black;
font-family:Verdana;
font-size: 1em;
	border-width: 1px;
	padding: 5px;
	font-weight:normal;
	border-color: red;
	background-color: beige;
	-moz-border-radius: ;
border:1px solid black;
}
</style>

</head>


<body>
<!-- google_ad_section_start -->
<?  include "dropdown_menu_for_malay.inc";  ?>

<table style="border:0;padding:0;margin:0;"><tr><td bgcolor="#CCFF99"><font face="Arial" size="2"><b>A basic course in Bahasa Malaysia (or Malaysian language - originally Malay language) &nbsp;<span style="font-size:smaller; color:black; font-weight:bolder; "><b> &copy;PJG</b></span></td>
</tr><tr><td bgcolor=orange><font face=Arial size=2 color=white><b><a href="http://pgoh13.com/amazon_malaylanguage.html" rel="nofollow" target="_blank"><font color=black>Books on Bahasa Malaysia.</font></a></td><!-- google_ad_section_end -->
</tr><tr><td bgcolor=midnightblue><font face=Arial size=2 color=white><b>These lessons are copyrighted and their publication in any form is strictly prohibited.</td>
</tr></table>

<br />

<div style="font-family:arial;font-size:1em;color:black;">Hi, welcome!
<br>Bahasa Malaysia is Malaysia's national language and is formerly known as Bahasa Melayu (Malay language).  It is not only spoken in Malaysia but is also widely spoken in Indonesia, Brunei and Singapore. Some people say that Bahasa Malaysia is an easy language.  To a certain extent it is, but believe me, it is not so easy that you can afford to study it while listening to your favourite music at the same time!
<br />The truth is there is no EASY language in the world.  Everything is relative so when people say that Malay is an easy language what they really mean is that it IS easy when compared to studying a language like English, French or Mandarin, for example.  Thus if you might need to spend at least 300 hours studying English, French or Mandarin before you are able to use it in a simple conversation, you need only spend say, 100 hours studying Malay before you are able to do so.   This is because in Malay there is no past tense or past participles of verbs to study as in English, the verbs are not conjugated as in French and you don't have to worry about getting the tones right in order to be understood as you have to in Mandarin.<br><br>