<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="bootstrap_malay.css" rel="stylesheet">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-4651027-4', 'auto');
  ga('send', 'pageview');
</script>

<br><br><a href="http://www2.clustrmaps.com/user/e65d40f9"><img src="http://www2.clustrmaps.com/stats/maps-no_clusters/pgoh13.com--thumb.jpg" height="2px" /></a>

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid"> <!-- this part stretches width to fill whole monitor -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" style="background-color:red;color:white;" href="http://pgoh13.com">The World At Your Fingertips&nbsp;<span class="glyphicon glyphicon-home glyphicon-large" aria-hidden="true"></span></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
<li class="active"><a href="http://pgoh13.com/mycourse/malay_introduction">Malay course</a></li>
<li><a href="http://pgoh13.com/francais/">En fran&ccedil;ais</a></li>
<li><a href="http://pgoh13.com/mobile/">Songs</a></li>
<li><a href="http://pgoh13.com/visiting_europe.php">Travel: Europe</a></li>
<li><a href="http://dictionary.pgoh13.com/">Malay dictionary</a></li>
<li><a href="http://pgoh13.com/about_pgoh13.php">About</a></li>
<li><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W">Contact&nbsp;<span class="glyphicon glyphicon-envelope glyphicon-large" aria-hidden="true"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container"> <!-- this part has fixed width -->
<p><em>Smartphone version.  The full version can be found <a href=http://pgoh13.com/mycourse/index.php>here.&nbsp;<span class="glyphicon glyphicon-link"></span></a></em></p>