<!DOCTYPE html>
<html lang="fr">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- without the js code below the dropdown menu won't work -->
<script>
$(document).ready( function() {
$('.dropdown-toggle').dropdown();
});
</script>

<link href="bootstrap_malay.css" rel="stylesheet">


</head>
<body>


<div class="container"> <!-- this part has fixed width -->
<table style="border-style:hidden;"><tr>
<td>
<b><a style="text-decoration:none;color:#00009C" href="table_contentsPC.htm" rel="nofollow">Table of Lessons (for PC)</a> &nbsp; | &nbsp;
<a style="text-decoration:none;color:#00009C" href=http://pgoh13.free.fr/>HOME PAGE</a>
</td></tr></table>
<p><em>This is the smartphone version.  The earlier and fuller version, which discusses the Indonesian language as well, can be found <a href=index.php>here.&nbsp;<span class="glyphicon glyphicon-link"></span></a></em></p>