<head>
<!-- Start css3menu.com HEAD section -->
<link rel="stylesheet" href="http://pgoh13.com/test_menu_files/css3menu1/style.css" type="text/css" />
<!-- End css3menu.com HEAD section -->


<script>
function getFocusGoogleCustomSearch()
{
 document.customsearchbox.q.focus();
}
</script>
</head>

<body>
<!-- Start css3menu.com BODY section id=1 -->

<center><nav>
<ul id="css3menu1" class="topmenu">
	<li class="topfirst"><a href="#" style="height:18px;line-height:18px;"><span>TRAVEL</span></a>
	<ul>
		<li><a href="http://pgoh13.com/europe.php"><span>Europe</span></a>
		<ul>
			<li><a href="http://pgoh13.com/paris_intro.php">Paris</a></li>
			<li><a href="http://pgoh13.com/rome.php">Rome</a></li>
			<li><a href="http://pgoh13.com/london.php">London</a></li>
			<li><a href="http://pgoh13.com/barcelona.php">Barcelona</a></li>
			<li><a href="http://pgoh13.com/madrid/">Madrid</a></li>
			<li><a href="http://pgoh13.com/venice.php">Venice</a></li>
			<li><a href="http://pgoh13.com/prague.php">Prague</a></li>
			<li><a href="http://pgoh13.com/amsterdam.php">Amsterdam</a></li>
			<li><a href="http://pgoh13.com/athens.php">Athens</a></li>
			<li><a href="http://pgoh13.com/copenhagen.php">Copenhagen</a></li>
			<li><a href="http://pgoh13.com/geneva.php">Geneva</a></li>
			<li><a href="http://pgoh13.com/andalucia.php">Andalucia</a></li>
			<li><a href="http://pgoh13.com/french_riviera.php">French Riviera</a></li>
			
		</ul></li>
		<li><a href="http://pgoh13.com/china.php"><span>China</span></a>
		<ul>
			<li><a href="http://pgoh13.com/zhouzhuang.php">Zhouzhuang</a></li>
			<li><a href="http://pgoh13.com/hangzhou.php">Hangzhou</a></li>
			<li><a href="http://pgoh13.com/xian.php">Xian</a></li>
			<li><a href="http://pgoh13.com/shanghai1.php">Shanghai</a></li>
			<li><a href="http://pgoh13.com/beijing_introduction.php">Beijing</a></li>
		</ul></li>
		<li><a href="http://pgoh13.com/Malaysia_new.php"><span>Malaysia</span></a>
		<ul>
			<li><a href="http://pgoh13.com/visit_perhentian.php">Perhentian Islands</a></li>
			<li><a href="http://pgoh13.com/visit_cameron.php">Cameron Highlands</a></li>
			<li><a href="http://pgoh13.com/visit_kb.php">Kota Bharu</a></li>
			<li><a href="http://pgoh13.com/visit_melaka.php">Malacca</a></li>
			<li><a href="http://pgoh13.com/visit_penang1.php">Penang</a></li>
			<li><a href="http://pgoh13.com/visit_kl.php">Kuala Lumpur</a></li>
		</ul></li>
		<li><a href="http://pgoh13.com/morocco.php"><span>Morocco</span></a>
		<ul>
			<li><a href="http://pgoh13.com/agadir.php">Agadir</a></li>
			<li><a href="http://pgoh13.com/rabat.php">Rabat</a></li>
			<li><a href="http://pgoh13.com/casablanca.php">Casablanca</a></li>
			<li><a href="http://pgoh13.com/marrakesh.php">Marrakesh</a></li>
		</ul></li>
	
<li><a href="http://www.easytobook.com/?amu=280822023" target="_blank">Online hotel booking</a></li>
<li><a href="http://www.worldtravelguide.net" target="_blank">World destinations</a></li>
	</ul></li>


	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>SONGS</span></a>
	<ul>
		<li><a href="http://blog.pgoh13.com/lyrics/">English Songs</a></li>
		<li><a href="http://blog.pgoh13.com/chansons/">French Songs</a></li>
		<li><a href="http://pgoh13.com/chinese_songs.php">Chinese Songs</a></li>
		<li><a href="http://pgoh13.com/malaysongs/">Malay Songs</a></li>
		<li><a href="http://pgoh13.com/spanishsongs/">Spanish Songs</a></li>
		
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>LANGUAGES</span></a>
	<ul>
		<li><a href="http://malay.pgoh13.com/">Malay Lessons</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_introduction.php">Chinese Pinyin Lessons</a></li>
		<li><a href="http://dictionary.pgoh13.com/">English-Malay Dictionary</a></li>
		<li><a href="http://pinyin.pgoh13.com/chinese_characters.php">Basic Chinese Characters</a></li>
<li><a href="http://www.word2word.com/course.html" target="_blank">All World Languages</a></li>
		
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>INFO</span></a>
	<ul>
	<li><a href="http://pgoh13.com/2013_calendar.php">2013 Calendar and Events</a></li>
	<li><a href="http://www.web-l.com/country-codes/" target="_blank">Country codes for internet</a></li>
	<li><a href="http://onlineconversion.com/" target="_blank">Conversions (length, weight, volume, temperature)</a></li>
	<li><a href="http://wwp.greenwichmeantime.com/time-zone/usa/eastern-time/convert/index.htm" target="_blank">Time Conversion:  EST to GMT</a></li>
	<li><a href="http://www.urbanrail.net/" target="_blank">World subways/metro</a></li>		
	<li><a href="http://www.infobel.com/world/default.asp" target="_blank">World telephone directories</a></li>
	<li><a href="http://embassyinformation.com/" target="_blank">World Embassies</a></li>
	<li><a href="http://www.journeymart.com/tools/world-holidays/default.aspx" target="_blank">World public holidays</a></li>
	<li><a href="http://www.seat61.com/" target="_blank">World train time-tables</a></li>
	<li><a href="http://www.timeanddate.com/worldclock/dialing.html" target="_blank">International Dialling Codes</a></li>
	<li><a href="http://pgoh13.com/converter_xe.php">Money converter</a></li>
	<li><a href="http://www.timeanddate.com/weather/" target="_blank">Today's weather</a></li>
	
	<li><a href="http://translate.google.com/" target="_blank">Anything to translate?</a></li>
	<li><a href="http://pgoh13.com/location_address.php">Get map for address</a></li>		
	</ul></li>
	
	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>INTERNET</span></a>
	<ul>
		<li><a href="http://pgoh13.com/software_progs1.php">Useful programs</a></li>
		<li><a href="http://pgoh13.com/internet_tips1.php">Internet/Computer tips</a></li>
		<li><a href="http://pgoh13.com/cobian_backup.php">Using Cobian Backup</a></li>
		<li><a href="http://pgoh13.com/rssreader_installation.php">Using the RssReader</a></li>
		<li><a href="http://pgoh13.com/copy_youtube.php">Tips for YouTube</a></li>
		<li><a href="http://pgoh13.com/spam_list.php">Email spams and scams</a></li>
		<li><a href="http://pgoh13.com/special_characters.php">Special characters</a></li>
	</ul></li>

	<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>LEISURE</span></a>
	<ul>
		<li><a href="http://pgoh13.com/justforlaughs.php">Just for laughs</a></li>
		<li><a href="http://pgoh13.com/brainteasers.php">Brainteasers</a></li>
		<li><a href="http://pgoh13.com/quotations.php">Inspiring quotations</a></li>
</ul></li>

<li class="topmenu"><a href="#" style="height:18px;line-height:18px;"><span>NEWS</span></a>
	<ul>
<li><a href="http://feeds.feedburner.com/newsy-allvideos" target="_blank">Video news from Newsy.com</a></li> 
<li><a href="http://www.huffingtonpost.com/?country=US" target="_blank">Huffington Post US</a></li>
<li><a href="http://www.huffingtonpost.co.uk/" target="_blank">Huffington Post UK</a></li>
<li><a href="http://www.bbc.com/" target="_blank">BBC (News headlines)</a></li> 
<li><a href="http://rss.cnn.com/rss/edition.rss" target="_blank">CNN (RSS feeds)</a></li>
<li><a href="http://www.buzzfeed.com/" target="_blank">BuzzFeed</a></li>
<li><a href="http://gawker.com/" target="_blank">Gawker</a></li>
<li><a href="http://www.thedailybeast.com/" target="_blank">The Daily Beast/Newsweek</a></li>
<li><a href="http://www.slate.com/" target="_blank">Slate magazine</a></li>
<li><a href="http://mashable.com/" target="_blank">Mashable</a></li>
<li><a href="http://pgoh13.com/4news_agencies.html" target="_blank">International news agencies</a></li> 
<li><a href="http://www.cbc.ca/news/" target="_blank">Top Canadian news</a></li> 
<li><a href="http://www.news.com.au/" target="_blank">Top Australian news</a></li>
<li><a href="http://pgoh13.com/periodicos.html" target="_blank">Spanish newspapers</a></li> 
<li><a href="http://pgoh13.com/deux_journaux.html" target="_blank">French newspapers</a></li> 
<li><a href="http://youtube-trends.blogspot.com/" target="_blank">YouTube trends</a></li> 
<li><a href="http://www.tmz.com" target="_blank">TMZ entertainment news</a></li>
</ul></li>

<li class="topmenu"><a href="http://pgoh13.com/health_page.php" style="height:18px;line-height:18px;">HEALTH</a></li>

<li class="topmenu"><a href="http://pgoh13.com/recipes_page.php" style="height:18px;line-height:18px;">FOOD</a></li>


<li class="topmenu"><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" target="_blank" style="height:18px;line-height:18px;">CONTACT</a></li>


<li class="toplast"><a href="http://pgoh13.com/about_pgoh13.php" target="_blank" style="height:18px;line-height:18px;">ABOUT</a></li>



</ul>

<form name="customsearchbox" action="http://www.google.co.uk" id="cse-search-box" target="_blank">
  <div>
    <input type="hidden" name="cx" value="partner-pub-3250339308164521:5475463726" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q" size="30" />
    <input type="submit" name="sa" value="Search Google" />
  </div>
<script type="text/javascript" src="http://www.google.co.uk/coop/cse/brand?form=cse-search-box&amp;lang=en"></script>
</form>

</nav></center>


<body onload="getFocusGoogleCustomSearch()">
<!-- End css3menu.com BODY section -->