
<style type="text/css">
a {text-decoration: none;}
a:hover {color:green;font-weight:bolder;}
</style>
<br>
<div style="width:780px;background-color:beige;margin-left:20px;margin-top:10px;padding-bottom:20px;font-family:arial;font-size:12px;font-weight:bold;border:1px solid black;padding:10px;text-align:left;"><strong>TRAVEL.  Places covered in this website: </strong>&nbsp;

<A href=milan.php>Milan</a> | 
<A href=lisbon.php>Lisbon</a> | 
<A href=dublin.php>Dublin</a> | 
<A href=sicily/>Sicily</a> | 
<A href=budapest.php>Budapest</a> | 
<A href=venice.php>Venice</a> | 
<A href=paris_page1.php>Paris</a> | 
<A href=madrid/>Madrid</a> | 
<A href=london.php>London</a> | 
<A href=barcelona.php>Barcelona</a> | 
<A href=rome.php>Rome</a> | 
<A href=naples.php>Naples</a> | 
<A href=french_riviera.php>Cannes</a> | 
<A href=french_riviera3.php>Monaco</a> | 
<A href=french_riviera2.php>Nice</a> | 
<A href=geneva.php>Geneva</a> | 
<A href=amsterdam.php>Amsterdam</a> | 
<A href=beijing_introduction.php>Beijing</a> | 
<A href=shanghai1.php>Shanghai</a> | 
<A href=xian.php>Xi'an</a> | 
<A href=hangzhou.php>Hangzhou</a> | 
<A href=marrakesh.php>Marrakesh</a> | 
<A href=casablanca.php>Casablanca</a> | 
<A href=visit_penang.php>Penang</a> | 
<A href=visit_kl.php>Kuala Lumpur</a> | 
<A href=visit_melaka.php>Malacca</a> | 
<A href=capri.php>Capri Island</a> | 
<A href=copenhagen.php>Copenhagen</a> | 
<A href=malmo.php>Malmo</a> | 
<A href=singapore.php>Singapore</a> | 
<A href=visit_perhentian.php>Perhentian Islands</a> | 
<A href=larochelle_intro.php>La Rochelle</a> | 
<A href=ile_dere.php>Ile de R&eacute;</a> | 
<A href=madrid/toledo.php>Toledo</a> | 
<A href=brighton_visit.php>Brighton</a> | 
<A href=oslo.php>Oslo</a> | 
<a href=athens.php>Athens</a> | 
<a href=andalucia.php>Andalucia</a> | 
<A href=prague.php>Prague</a> | 
<A href=rouen.php>Rouen</a> | 
<A href=kent/>Kent</a>
<br><span style="display:block;width:120px;float:right;">Copyright &copy; pgoh13</span>

</center>

</div>
