<!-- Start css3menu.com HEAD section -->

<link rel="stylesheet" href="http://pgoh13.com/test_menu_files/css3menu1/style.css" type="text/css" />

<!-- End css3menu.com HEAD section -->



<style type="text/css">
<!--
 .al { text-align : justify; font-family : verdana,arial,times}
 a:hover {background:yellow; color : blue}
a {text-decoration:none }
-->
.white {color:white}
table.heading td {
font: bold 32pt verdana, arial, sans-serif;
color:red; background-color:yellow}

h1 {	font-family:"Arial";
	font-size: 36px;
	color:yellow;
	text-align:center;background-color:midnightblue;padding:0 20px;margin:0 auto;display:inline-block;	
   }
h2 {	font-family:"Arial";
	font-size: 24px;
	color:yellow;
	text-align:center;	
   }
h3 {	font-family:"Arial";
	font-size: 18px;
	color:#00FF00;
	text-align:center;	
   }
</style>
