<div id="travelbar-container"><div id="travelbar"><font color=red>
<font color=black><b>This site is optimized for 1024 x 768 screen resolution and tested with Firefox.  It might not display correctly in smartphones or other browsers.</b></font>
<br />TRAVEL:</font>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://pgoh13.com/venice.php" target="_blank">Venice</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/london.php" target="_blank">London</a>&nbsp;&nbsp;

<a href="http://pgoh13.com/barcelona.php" target="_blank">Barcelona</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/madrid/" target="_blank">Madrid</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/rome.php" target="_blank">Rome</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/naples.php" target="_blank">Naples</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/paris_page1.php" target="_blank">Paris</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/french_riviera.php" target="_blank">French Riviera</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/geneva.php" target="_blank">Geneva</a>&nbsp;&nbsp;&nbsp;
<a href="http://pgoh13.com/amsterdam.php" target="_blank">Amsterdam</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/beijing_introduction.php" target="_blank">Beijing</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/shanghai1.php" target="_blank">Shanghai</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/marrakesh.php" target="_blank">Marrakesh</a>&nbsp;&nbsp;
<a href="http://pgoh13.com/casablanca.php" target="_blank">Casablanca</a>

<br /><b>To find this site from a cybercafe or the public library just type <a href=http://www.google.com/search?q=pgoh13 target=_blank><font color=red>pgoh13</font></a> in the search engine box.</b>
</div>
</div>
