<style type="text/css">
body  {background-color:#cccccc;}
body:after {font-style:italic;border:0;content:"Copyrighted.  Not to be reproduced without permission from pgoh13";}
.malay {color:blue;font-family:arial;font-size:12pt;font-weight:normal;padding:2px 10px;}
table {border-collapse: collapse;
	border:1px solid black;}
 td.table1 {background-color:black;padding:1px;}
 td.table2 {font-family:arial;font-size:12pt;padding:2px 10px 2px 10px;border:1px solid black;}

table.noborder {border:0;}
div {color:red;}
.otherlinks {color:#00009C;font-weight:normal;}
.al {text-align:justify; font-family:verdana,arial,times;}
a {text-decoration:none;color:white;font-weight:bold;}
a:link {}
a:visited {}
a:hover {background:yellow; color:red;}
a:active {}
img { border: 0; }

h1 {	font-family:arial;
	font-size: 30px;
	color:yellow;
	border:0 15px;
	text-align:center;
	margin-top:0; /* so there won't be spacing above h1  */
	}

h2 {font-family:arial;
	font-size: 18px;
	color:white;
	text-align:left;
	}

p {font-family:tahoma,verdana,arial;
	font-size: 16px;
	text-align:left;
	margin-left:10px;}
p b {font-family:arial;font-size:12pt;color:#00009C;font-weight:normal;}
p.greenpara {font-family:"comic sans ms",verdana,arial;
	font-size: 12px;
	color:green;
	text-align:justify;
	margin-left:0px;}
</style>