<!DOCTYPE html>
<html><head>
<meta name="viewport" content="width = 980" />
<link rel="shortcut icon" href="http://pgoh13.com/favicon.ico" rel="nofollow"> 

<style>
.gray {color:gray}
.green {color:green}
.lightgreen {color:lightgreen}
.darkorange {color:darkorange}
.orange {color:yellow}
.blue {color:blue}
.red {color:red}
.white {color:white}
.silver {color:silver}
.yellow1 {color:#FFFC17}
.darkpurple {color:darkpurple}
.black {color:black}
.midnightblue {color:midnightblue}
.malayword {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
.yellow {font-family: "century gothic"; color: red; font-size:18px}
.yellow2 {color:yellow}
.inmalay {font-family: "century gothic"; color: "#0000FF"; font-size:18px}
</style>

<STYLE TYPE="text/css">
<!--
 .al { text-align : justify; font-family : verdana,arial,times}
 A:hover {background:yellow; color : blue}
A {text-decoration:none }
-->
</STYLE>

<script language="JavaScript">
function focusIt(ele)
{
ele.focus();
}
</script>
<?/* above script replaces this one
<script type="text/javascript">
  function setfocus()
  {
    document.forms[0].q.focus()
  }
  </script>
<font size=1>
<br /><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" rel="nofollow" title="Contact Form" target="_blank" class=white>Email/Contact/Feedback</a>
<br /><a href="http://pgoh13.com/about_us.php" rel="nofollow" title="About"  class=white target=_blank>About us</a>
 */?>

<script type="text/javascript">
function mailto(domain,user) 
{ 
document.location.href = "mailto:" + user + "@" + domain;
}
</script>

<style type="text/css">
table.pleasenote2 {
border-color: darkblue; border-width:0; border-style:solid;
margin: 5px}
table.pleasenote2 td {
font: bold 10pt verdana, arial, sans-serif;
color:yellow; background-color:black}
table.heading td {
font: bold 20pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote3 td {text-align:left;
font: normal 8pt verdana, arial, sans-serif;
color:red; background-color:yellow; border-style:solid;
	border-width:1px;
	border-color:black;} 
table.heading td {
font: bold 12pt verdana, arial, sans-serif;
color:red; background-color:yellow}
table.pleasenote4 {
border-color: darkblue; border-width:2; border-style:solid;
margin: 2px}
table.pleasenote4 td {
font: normal 12pt verdana, arial, sans-serif;
color:midnightblue; background-color:beige} 
table.heading td {
font: bold 32pt verdana, arial, sans-serif;
color:red; background-color:yellow}
</style>
<style type="text/css">
h1 {	font-family:"Arial";
	font-size: 30px;
	color:yellow;
	text-align:center;	
   }
h2 {	font-family:"Arial";
	font-size: 24px;
	color:yellow;
	text-align:center;	
   }
h3 {	font-family:"Arial";
	font-size: 18px;
	color:#00FF00;
	text-align:center;	
   }
</style>

<style type="text/css">
.typeface {font-family:tahoma;
font-size: 16px;
font-weight:bold;}
</style>

<script>
function setFocusToTextBox(){
    document.getElementById("mytext").focus();
}
</script>

</head>

<body bgcolor=#cccccc onload='setFocusToTextBox()'>

<!-- FreeFind Begin No Index -->
<nav>
<table style="width:180px;border:1px solid black;background-color:beige;padding:0 5px;"><tr><td><em style="font-size:0.8em;font-weight:bold;">By using this website, you agree to the use of cookies and terms of service as described <a href=http://pgoh13.com/terms_conditions.php>here.</a></em></td></tr></table>

<table bgcolor=black width="180" border=0><tr><td>
<font face=arial size=2>
<b><A href="http://pgoh13.com/" rel="nofollow" title="The world at your fingertips"  class=white target=_blank>Home Page</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=http://feeds.feedburner.com/RssFeedsFromPgoh13com rel="nofollow" title="RSS feeds" target=_blank><img src=http://pgoh13.com/rss_combined.gif rel="nofollow"></a>
<br /><a href="http://pgoh13.com/francais" rel="nofollow" target=_blank class=white>En fran&ccedil;ais &nbsp;<img src=flag_french.gif></a>
<br /><a href="http://pgoh13.com/2016_calendar.php" rel="nofollow" title="2016 Calendar/Events" class=white>2016 Calendar/Events</a>
<br /><a href="http://pgoh13.com/timeat_aglance.php" rel="nofollow" class=white>Get the exact time</a>
<br /><a href="http://www.timeanddate.com/weather/" rel="nofollow" target=_blank class=white>Get present weather</a>
<br /><a href="http://pgoh13.com/converter_xe.php" rel="nofollow" target=_blank class=white>Your money converter</a>
<br />
<a href="http://pgoh13.com/location_address.php" rel="nofollow" target=_blank class=white>Google maps</a>
<br />
<form method="get" target="_blank" action="http://dictionary.reference.com/search">
<table width="170" border="0" cellspacing="4" cellpadding="4" bgcolor="#000000">
<tr>
<td valign="middle" align="left">
<strong style="font-family: arial,helvetica,sans-serif; font-size: 100%; color: #ffffff;">English dictionary:</strong>
<input type="text" name="q" size="10" maxlength="50" style="font-size:11pt;">
<input type="submit" value="GO" style="font-weight:normal; font-size:11pt; font-family: arial,helvetica,sans-serif;">
</td>
</tr>
</table>
</form>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://www.bing.com/translator/" rel="nofollow" title="Bing Translator"  class=white target=_blank>Bing Translator</a>
<br><A href="http://translate.google.com/" rel="nofollow" title="Google Translate" class=white target=_blank>Google Translate</a>
<br /><a href="http://pgoh13.com/site_index.html" rel="nofollow" title="Sitemap of The World At Your Fingertips"  class=white target=_blank>Sitemap (Index to site)</a>
<br /><A href="http://pgoh13.com/worlds_myhome.php" rel="nofollow" title="The World's My Home"  class=white target=_blank>The World's My Home</a>
<br /><A href="http://pgoh13.com/tourist_destinations.php" rel="nofollow" title="Popular tourist destinations"  class=white target=_blank>Popular destinations</a>
<br /><A href="http://pgoh13.com/europe.php" rel="nofollow" title="Visiting Europe's top cities"  class=white target=_blank>Visiting Europe</a>
<br /><A href="http://pgoh13.com/china.php" rel="nofollow" title="Visiting China"  class=white target=_blank>Visiting China</a>
<br /><A href="http://pgoh13.com/morocco.php" rel="nofollow" title="Visiting Morocco"  class=white target=_blank>Visiting Morocco</a>
<br /><A href="http://pgoh13.com/Malaysia_new.php" rel="nofollow" title="Visiting Malaysia"  class=white target=_blank>Visiting Malaysia</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://pgoh13.com/control_button.php" rel="nofollow" title="The Ctrl button" class=white>The Ctrl button</a>
<br><A href="http://pgoh13.com/copy_youtube.php" rel="nofollow" title="How to copy YouTube clips to your hard disk" class=white>Useful tips for YouTube</a>
<br /><A href="http://pgoh13.com/password_creating.php" rel="nofollow" title="How to create your own password" class=white>Your own password</a>
<br /><A href="http://pgoh13.com/using_teamviewer.php" rel="nofollow" title="Using TeamViewer" class=white>Using TeamViewer</a>
<br /><A href="http://pgoh13.com/using_partitionwizard.php" rel="nofollow" title="Using Partition Wizard" class=white>Using Partition Wizard</a>
<br /><A href="http://pgoh13.com/using_printedit.php" rel="nofollow" title="Using Print Edit" class=white>Using Print Edit</a>
<br /><A href="http://pgoh13.com/using_hola.php" rel="nofollow" title="Using Hola! to access blocked websites" class=white>Using Hola!</a>
<br /><A href="http://pgoh13.com/internet_tips1.php" rel="nofollow" title="Getting the most out of Internet" class=white>Internet/Computer tips</a>
<br /><A href="http://pgoh13.com/software_progs1.php" rel="nofollow" title="Free and useful software to install" class=white>Useful software</a>
<br /><A href="http://pgoh13.com/quotations.php" rel="nofollow" title="Inspiring quotations and ideas" class=white>Inspiring quotes/ideas</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://pgoh13.com/health_page.php" rel="nofollow" title="Health topics" class=white>Health topics</a>
<br /><a href="http://pgoh13.com/recipes_page.php" rel="nofollow" title="Food recipes" class=white>Food recipes</a>
<br /><a href="http://pgoh13.com/brainteasers.php" rel="nofollow" title="Brainteasers 1" class=white>Brainteasers</a>
<br /><A href="http://pgoh13.com/justforlaughs.php" rel="nofollow" title="No kidding: this is the world's funniest joke"  class=white>Just for laughs</a>
<br /><a href="http://pgoh13.com/pensioners_page.php" rel="nofollow" class=white>Page for senior citizens</a>
<br /><A href="http://pgoh13.com/spam_list.php" rel="nofollow" title="Email spams and scams" class=white>Email spams and scams</a>
<br /><A href="http://pgoh13.com/special_characters.php" rel="nofollow" title="How to type special characters" class=white>Those special characters</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><a href="http://pgoh13.com/oldsongs_newsingers.php" rel="nofollow" title="Old songs new singers" class=white target="_blank">Old songs new singers</a>
<br /><A href="http://pgoh13.com/deezer/" rel="nofollow" title="Deezer playlists" class=white target="_blank">Deezer playlists</a>
<br /><a href="http://pgoh13.com/greatest_french_songs.php" rel="nofollow" title="The greatest French songs of all time" class=white target="_blank">Greatest French songs</a>
<br /><a href="http://pgoh13.com/greatest_english_songs.php" rel="nofollow" title="List of 1,000 English songs in Songs and Lyrics" class=white target="_blank">1,000 English songs</a>
<br /><a href="http://pgoh13.com/songs/" rel="nofollow" target="_blank" title="Evergreens/Oldies" class=white>Evergreens/Oldies</a>
<br /><A href="http://pgoh13.com/chinese_songs.php" rel="nofollow" title="Chinese songs" class=white target="_blank">Chinese songs</a>
<br /><A href="http://pgoh13.com/malaysongs/" rel="nofollow" title="Malay songs" class=white target="_blank">Malay songs</a>
<br /><A href="http://pgoh13.com/spanishsongs/" rel="nofollow" title="Spanish songs" class=white target="_blank">Spanish songs</a>
</td></tr></table>

<table width=180><tr><td width="100%" bgcolor=black>
<font face=arial size=2>
<b><A href="http://pinyin.pgoh13.com/chinese_introduction.php" rel="nofollow" title="Learn to speak Chinese"  class=white target=_blank>Learn Chinese pinyin</a>
<br /><A href="http://pinyin.pgoh13.com/chinese_characters.php" rel="nofollow" title="Chinese characters" class=white>Chinese characters</a>
<br /><A href="http://dictionary.pgoh13.com/" rel="nofollow" title="English-Malay Dictionary" class=white>English-Malay Dictionary</a>
<br /><A href="http://pgoh13.com/mycourse/" rel="nofollow" title="Malaysian language" class=white target=_blank>Malaysian language</a>
<br /><a href="http://www.emailmeform.com/builder/form/Vr4xzDPmb4W" rel="nofollow" class="white" target=_blank>Contact &nbsp;<img src=envelope.gif></a>
<br /><a href="http://pgoh13.com/about_pgoh13.php" rel="nofollow" class="white" target="_blank">About</a>
<br /><a href="http://pgoh13.com/privacy_policy.php" rel="nofollow" class="white" target="_blank">Privacy policy</a>
</font>
</nav>

<br /><br />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- asyn_linkunit_160x90 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:90px"
     data-ad-client="ca-pub-3250339308164521"
     data-ad-slot="3235793325"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</b></td></tr></table>

<?/* <br><a href="http://www2.clustrmaps.com/user/e65d40f9"><img src="http://www2.clustrmaps.com/stats/maps-no_clusters/pgoh13.com--thumb.jpg" height="2px" /></a>

 <br>
<!-- Site Meter -->
<script type="text/javascript" src="http://s26.sitemeter.com/js/counter.js?site=s26focusmalaysia" target="_blank">
</script>
<noscript>
<a href="http://s26.sitemeter.com/stats.asp?site=s26focusmalaysia" target="_blank">
<img src="http://s26.sitemeter.com/meter.asp?site=s26focusmalaysia" alt="Site Meter" border="0"/></a>
</noscript>
<!-- Copyright (c)2009 Site Meter -->

<a href="http://www.xiti.com/xiti.asp?s=363353" title="WebAnalytics" target="_top">
<script type="text/javascript">
<!--
Xt_param = 's=363353&p=';
try {Xt_r = top.document.referrer;}
catch(e) {Xt_r = document.referrer; }
Xt_h = new Date();
Xt_i = '<img width="10" height="2" border="0" alt="" ';
Xt_i += 'src="http://logv3.xiti.com/hit.xiti?'+Xt_param;
Xt_i += '&hl='+Xt_h.getHours()+'x'+Xt_h.getMinutes()+'x'+Xt_h.getSeconds();
if(parseFloat(navigator.appVersion)>=4)
{Xt_s=screen;Xt_i+='&r='+Xt_s.width+'x'+Xt_s.height+'x'+Xt_s.pixelDepth+'x'+Xt_s.colorDepth;}
document.write(Xt_i+'&ref='+Xt_r.replace(/[<>"]/g, '').replace(/&/g, '$')+'" title="Internet Audience">');
//-->
</script>
<noscript>
Mesure d'audience ROI statistique webanalytics par <img width="39" height="25" src="http://logv3.xiti.com/hit.xiti?s=363353&p=" alt="WebAnalytics" />
</noscript></a>
*/ ?>

<!-- google_ad_section_end(weight=ignore) -->
<!-- google_ad_section_start -->